using System;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Text;
using System.Windows.Forms;
using Guna.UI2.WinForms;
using InvokedServer.Controls;
using InvokedServer.Properties;

namespace InvokedServer.Forms
{
    partial class FrmHiddenBrowser
    {
        private IContainer components;

        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null)
                this.components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = (IContainer)new System.ComponentModel.Container();
            ComponentResourceManager resources = new ComponentResourceManager(typeof(FrmHiddenBrowser));
            this.btnStart = new Button();
            this.btnStop = new Button();
            this.barQuality = new TrackBar();
            this.lblQuality = new Label();
            this.lblQualityShow = new Label();
            this.btnMouse = new Button();
            this.panelTop = new Panel();
            this.ExtraBtn = new Guna2Button();
            this.CloneBrowserCheckbox = new CheckBox();
            this.HiddenEdgeBtn = new Button();
            this.HiddenBraveBtn = new Button();
            this.HiddenFirefoxBtn = new Button();
            this.HiddenChromeBtn = new Button();
            this.PowershellBtn = new Button();
            this.CmdBtn = new Button();
            this.FullScreen = new Button();
            this.btnKeyboard = new Button();
            this.btnHide = new Button();
            this.hVNCContextMenuStrip = new Guna2ContextMenuStrip();
            this.ResetAllWindowsToolStripMenuItem = new ToolStripMenuItem();
            this.btnShow = new Button();
            this.toolTipButtons = new ToolTip(this.components);
            this.hvncPictureBox1 = new hvncPictureBox();
            this.barQuality.BeginInit();
            this.panelTop.SuspendLayout();
            this.hVNCContextMenuStrip.SuspendLayout();
            ((ISupportInitialize)this.hvncPictureBox1).BeginInit();
            this.SuspendLayout();
            this.btnStart.Location = new Point(15, 5);
            this.btnStart.Name = "btnStart";
            this.btnStart.Size = new Size(68, 23);
            this.btnStart.TabIndex = 1;
            this.btnStart.TabStop = false;
            this.btnStart.Text = "Start";
            this.btnStart.UseVisualStyleBackColor = true;
            this.btnStart.Click += new EventHandler(this.btnStart_Click);
            this.btnStop.Enabled = false;
            this.btnStop.Location = new Point(96, 5);
            this.btnStop.Name = "btnStop";
            this.btnStop.Size = new Size(68, 23);
            this.btnStop.TabIndex = 2;
            this.btnStop.TabStop = false;
            this.btnStop.Text = "Stop";
            this.btnStop.UseVisualStyleBackColor = true;
            this.btnStop.Click += new EventHandler(this.btnStop_Click);
            this.barQuality.Location = new Point(206, -1);
            this.barQuality.Maximum = 100;
            this.barQuality.Minimum = 1;
            this.barQuality.Name = "barQuality";
            this.barQuality.Size = new Size(76, 45);
            this.barQuality.TabIndex = 3;
            this.barQuality.TabStop = false;
            this.barQuality.Value = 100;
            this.barQuality.Scroll += new EventHandler(this.barQuality_Scroll);
            this.lblQuality.AutoSize = true;
            this.lblQuality.Location = new Point(167, 5);
            this.lblQuality.Name = "lblQuality";
            this.lblQuality.Size = new Size(46, 13);
            this.lblQuality.TabIndex = 4;
            this.lblQuality.Text = "Quality:";
            this.lblQualityShow.AutoSize = true;
            this.lblQualityShow.Location = new Point(220, 26);
            this.lblQualityShow.Name = "lblQualityShow";
            this.lblQualityShow.Size = new Size(56, 13);
            this.lblQualityShow.TabIndex = 5;
            this.lblQualityShow.Text = "100 (best)";
            this.btnMouse.Image = (Image)Resources.mouse_add;
            this.btnMouse.Location = new Point(297, 5);
            this.btnMouse.Name = "btnMouse";
            this.btnMouse.Size = new Size(28, 28);
            this.btnMouse.TabIndex = 6;
            this.btnMouse.TabStop = false;
            this.toolTipButtons.SetToolTip((Control)this.btnMouse, "Enable mouse input.");
            this.btnMouse.UseVisualStyleBackColor = true;
            this.btnMouse.Click += new EventHandler(this.btnMouse_Click);
            this.panelTop.BorderStyle = BorderStyle.FixedSingle;
            this.panelTop.Controls.Add((Control)this.ExtraBtn);
            this.panelTop.Controls.Add((Control)this.CloneBrowserCheckbox);
            this.panelTop.Controls.Add((Control)this.HiddenEdgeBtn);
            this.panelTop.Controls.Add((Control)this.HiddenBraveBtn);
            this.panelTop.Controls.Add((Control)this.HiddenFirefoxBtn);
            this.panelTop.Controls.Add((Control)this.HiddenChromeBtn);
            this.panelTop.Controls.Add((Control)this.PowershellBtn);
            this.panelTop.Controls.Add((Control)this.CmdBtn);
            this.panelTop.Controls.Add((Control)this.FullScreen);
            this.panelTop.Controls.Add((Control)this.btnKeyboard);
            this.panelTop.Controls.Add((Control)this.btnHide);
            this.panelTop.Controls.Add((Control)this.lblQualityShow);
            this.panelTop.Controls.Add((Control)this.btnMouse);
            this.panelTop.Controls.Add((Control)this.btnStart);
            this.panelTop.Controls.Add((Control)this.btnStop);
            this.panelTop.Controls.Add((Control)this.lblQuality);
            this.panelTop.Controls.Add((Control)this.barQuality);
            this.panelTop.Location = new Point(167, -1);
            this.panelTop.Name = "panelTop";
            this.panelTop.Size = new Size(420, 81);
            this.panelTop.TabIndex = 7;
            this.ExtraBtn.DisabledState.BorderColor = Color.DarkGray;
            this.ExtraBtn.DisabledState.CustomBorderColor = Color.DarkGray;
            this.ExtraBtn.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.ExtraBtn.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.ExtraBtn.Font = new Font("Segoe UI", 9f);
            this.ExtraBtn.ForeColor = Color.White;
            this.ExtraBtn.Location = new Point(27, 51);
            this.ExtraBtn.Name = "ExtraBtn";
            this.ExtraBtn.Size = new Size(67, 21);
            this.ExtraBtn.TabIndex = 26;
            this.ExtraBtn.Text = "Extra";
            this.ExtraBtn.Click += new EventHandler(this.ExtraBtn_Click);
            this.CloneBrowserCheckbox.AutoSize = true;
            this.CloneBrowserCheckbox.Location = new Point(282, 34);
            this.CloneBrowserCheckbox.Name = "CloneBrowserCheckbox";
            this.CloneBrowserCheckbox.Size = new Size(129, 17);
            this.CloneBrowserCheckbox.TabIndex = 24;
            this.CloneBrowserCheckbox.Text = "Clone Main Browser";
            this.CloneBrowserCheckbox.UseVisualStyleBackColor = true;
            this.HiddenEdgeBtn.BackColor = SystemColors.ActiveCaption;
            this.HiddenEdgeBtn.Enabled = false;
            this.HiddenEdgeBtn.FlatStyle = FlatStyle.Flat;
            this.HiddenEdgeBtn.Image = (Image)Resources.edge;
            this.HiddenEdgeBtn.Location = new Point(266, 55);
            this.HiddenEdgeBtn.Name = "HiddenEdgeBtn";
            this.HiddenEdgeBtn.Size = new Size(23, 23);
            this.HiddenEdgeBtn.TabIndex = 19;
            this.HiddenEdgeBtn.TabStop = false;
            this.toolTipButtons.SetToolTip((Control)this.HiddenEdgeBtn, "Launch Edge");
            this.HiddenEdgeBtn.UseVisualStyleBackColor = false;
            this.HiddenEdgeBtn.Click += new EventHandler(this.HiddenEdgeBtn_Click);
            this.HiddenBraveBtn.BackColor = SystemColors.ActiveCaption;
            this.HiddenBraveBtn.Enabled = false;
            this.HiddenBraveBtn.FlatStyle = FlatStyle.Flat;
            this.HiddenBraveBtn.Image = (Image)Resources.Brave_icon_lionface;
            this.HiddenBraveBtn.Location = new Point(388, 51);
            this.HiddenBraveBtn.Name = "HiddenBraveBtn";
            this.HiddenBraveBtn.Size = new Size(23, 23);
            this.HiddenBraveBtn.TabIndex = 22;
            this.HiddenBraveBtn.TabStop = false;
            this.toolTipButtons.SetToolTip((Control)this.HiddenBraveBtn, "Launch Brave");
            this.HiddenBraveBtn.UseVisualStyleBackColor = false;
            this.HiddenBraveBtn.Click += new EventHandler(this.HiddenBraveBtn_Click);
            this.HiddenFirefoxBtn.BackColor = SystemColors.ActiveCaption;
            this.HiddenFirefoxBtn.Enabled = false;
            this.HiddenFirefoxBtn.FlatStyle = FlatStyle.Flat;
            this.HiddenFirefoxBtn.Image = (Image)Resources.Firefox_logo;
            this.HiddenFirefoxBtn.Location = new Point(331, 51);
            this.HiddenFirefoxBtn.Name = "HiddenFirefoxBtn";
            this.HiddenFirefoxBtn.Size = new Size(23, 23);
            this.HiddenFirefoxBtn.TabIndex = 21;
            this.HiddenFirefoxBtn.TabStop = false;
            this.toolTipButtons.SetToolTip((Control)this.HiddenFirefoxBtn, "Launch Firefox");
            this.HiddenFirefoxBtn.UseVisualStyleBackColor = false;
            this.HiddenFirefoxBtn.Click += new EventHandler(this.HiddenFirefoxBtn_Click);
            this.HiddenChromeBtn.BackColor = SystemColors.ActiveCaption;
            this.HiddenChromeBtn.Enabled = false;
            this.HiddenChromeBtn.FlatStyle = FlatStyle.Flat;
            this.HiddenChromeBtn.Image = (Image)Resources.Google_Chrome_icon;
            this.HiddenChromeBtn.Location = new Point(297, 51);
            this.HiddenChromeBtn.Name = "HiddenChromeBtn";
            this.HiddenChromeBtn.Size = new Size(23, 23);
            this.HiddenChromeBtn.TabIndex = 20;
            this.HiddenChromeBtn.TabStop = false;
            this.toolTipButtons.SetToolTip((Control)this.HiddenChromeBtn, "Launch Chrome");
            this.HiddenChromeBtn.UseVisualStyleBackColor = false;
            this.HiddenChromeBtn.Click += new EventHandler(this.HiddenChromeBtn_Click);
            this.PowershellBtn.Enabled = false;
            this.PowershellBtn.Image = (Image)Resources.powershellicon;
            this.PowershellBtn.Location = new Point(153, 55);
            this.PowershellBtn.Name = "PowershellBtn";
            this.PowershellBtn.Size = new Size(23, 23);
            this.PowershellBtn.TabIndex = 13;
            this.PowershellBtn.TabStop = false;
            this.toolTipButtons.SetToolTip((Control)this.PowershellBtn, "Launch Powershell");
            this.PowershellBtn.UseVisualStyleBackColor = true;
            this.PowershellBtn.Click += new EventHandler(this.PowershellBtn_Click);
            this.CmdBtn.Enabled = false;
            this.CmdBtn.Image = (Image)Resources.CMDIcon;
            this.CmdBtn.Location = new Point(124, 55);
            this.CmdBtn.Name = "CmdBtn";
            this.CmdBtn.Size = new Size(23, 23);
            this.CmdBtn.TabIndex = 12;
            this.CmdBtn.TabStop = false;
            this.toolTipButtons.SetToolTip((Control)this.CmdBtn, "Launch cmd.exe");
            this.CmdBtn.UseVisualStyleBackColor = true;
            this.CmdBtn.Click += new EventHandler(this.CmdBtn_Click);
            this.FullScreen.Image = (Image)Resources.fullscreen;
            this.FullScreen.Location = new Point(365, 5);
            this.FullScreen.Name = "FullScreen";
            this.FullScreen.Size = new Size(28, 28);
            this.FullScreen.TabIndex = 10;
            this.FullScreen.TextAlign = ContentAlignment.MiddleRight;
            this.FullScreen.UseVisualStyleBackColor = true;
            this.FullScreen.Click += new EventHandler(this.FullScreen_Click);
            this.btnKeyboard.Image = (Image)Resources.keyboard_add;
            this.btnKeyboard.Location = new Point(331, 5);
            this.btnKeyboard.Name = "btnKeyboard";
            this.btnKeyboard.Size = new Size(28, 28);
            this.btnKeyboard.TabIndex = 9;
            this.btnKeyboard.TabStop = false;
            this.toolTipButtons.SetToolTip((Control)this.btnKeyboard, "Enable keyboard input.");
            this.btnKeyboard.UseVisualStyleBackColor = true;
            this.btnKeyboard.Click += new EventHandler(this.btnKeyboard_Click);
            this.btnHide.Location = new Point(182, 59);
            this.btnHide.Name = "btnHide";
            this.btnHide.Size = new Size(54, 19);
            this.btnHide.TabIndex = 7;
            this.btnHide.TabStop = false;
            this.btnHide.Text = "Hide";
            this.btnHide.UseVisualStyleBackColor = true;
            this.btnHide.Click += new EventHandler(this.btnHide_Click);
            this.hVNCContextMenuStrip.Items.AddRange(new ToolStripItem[1]
            {
                (ToolStripItem) this.ResetAllWindowsToolStripMenuItem
            });
            this.hVNCContextMenuStrip.Name = "hVNCContextMenuStrip";
            this.hVNCContextMenuStrip.RenderStyle.ArrowColor = Color.FromArgb(151, 143, (int)byte.MaxValue);
            this.hVNCContextMenuStrip.RenderStyle.BorderColor = Color.Gainsboro;
            this.hVNCContextMenuStrip.RenderStyle.ColorTable = (ProfessionalColorTable)null;
            this.hVNCContextMenuStrip.RenderStyle.RoundedEdges = true;
            this.hVNCContextMenuStrip.RenderStyle.SelectionArrowColor = Color.White;
            this.hVNCContextMenuStrip.RenderStyle.SelectionBackColor = Color.FromArgb(100, 88, (int)byte.MaxValue);
            this.hVNCContextMenuStrip.RenderStyle.SelectionForeColor = Color.White;
            this.hVNCContextMenuStrip.RenderStyle.SeparatorColor = Color.Gainsboro;
            this.hVNCContextMenuStrip.RenderStyle.TextRenderingHint = TextRenderingHint.SystemDefault;
            this.hVNCContextMenuStrip.Size = new Size(172, 26);
            this.ResetAllWindowsToolStripMenuItem.Name = "ResetAllWindowsToolStripMenuItem";
            this.ResetAllWindowsToolStripMenuItem.Size = new Size(171, 22);
            this.ResetAllWindowsToolStripMenuItem.Text = "Reset All Windows";
            this.ResetAllWindowsToolStripMenuItem.Click += new EventHandler(this.MoveWindowsToolStripMenuItem_Click);
            this.btnShow.Location = new Point(0, 0);
            this.btnShow.Name = "btnShow";
            this.btnShow.Size = new Size(54, 19);
            this.btnShow.TabIndex = 8;
            this.btnShow.TabStop = false;
            this.btnShow.Text = "Show";
            this.btnShow.UseVisualStyleBackColor = true;
            this.btnShow.Visible = false;
            this.btnShow.Click += new EventHandler(this.btnShow_Click);
            this.hvncPictureBox1._enableKeyboardInput = false;
            this.hvncPictureBox1._enableMouseInput = false;
            this.hvncPictureBox1.BackColor = SystemColors.Desktop;
            this.hvncPictureBox1.BorderStyle = BorderStyle.FixedSingle;
            this.hvncPictureBox1.Dock = DockStyle.Fill;
            this.hvncPictureBox1.GetImageSafe = (Image)null;
            this.hvncPictureBox1.Location = new Point(0, 0);
            this.hvncPictureBox1.Name = "hvncPictureBox1";
            this.hvncPictureBox1.Running = false;
            this.hvncPictureBox1.Size = new Size(786, 569);
            this.hvncPictureBox1.SizeMode = PictureBoxSizeMode.StretchImage;
            this.hvncPictureBox1.TabIndex = 9;
            this.hvncPictureBox1.TabStop = false;
            this.AutoScaleDimensions = new SizeF(96f, 96f);
            this.AutoScaleMode = AutoScaleMode.Dpi;
            this.ClientSize = new Size(786, 569);
            this.Controls.Add((Control)this.btnShow);
            this.Controls.Add((Control)this.panelTop);
            this.Controls.Add((Control)this.hvncPictureBox1);
            this.Font = new Font("Segoe UI", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte)0);
            this.Icon = (Icon)resources.GetObject("$this.Icon");
            this.KeyPreview = true;
            this.MinimumSize = new Size(640, 480);
            this.Name = "FrmHiddenBrowser";
            this.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "HVNC []";
            this.FormClosing += new FormClosingEventHandler(this.FrmHVNC_FormClosing);
            this.Load += new EventHandler(this.FrmHVNC_Load);
            this.Resize += new EventHandler(this.FrmHVNC_Resize);
            this.barQuality.EndInit();
            this.panelTop.ResumeLayout(false);
            this.panelTop.PerformLayout();
            this.hVNCContextMenuStrip.ResumeLayout(false);
            ((ISupportInitialize)this.hvncPictureBox1).EndInit();
            this.ResumeLayout(false);
        }

        private Button btnStart;
        private Button btnStop;
        private TrackBar barQuality;
        private Label lblQuality;
        private Label lblQualityShow;
        private Button btnMouse;
        private Panel panelTop;
        private Button btnHide;
        private Button btnShow;
        private Button btnKeyboard;
        private ToolTip toolTipButtons;
        private Button FullScreen;
        private hvncPictureBox hvncPictureBox1;
        private Button CmdBtn;
        private Button PowershellBtn;
        private Button HiddenEdgeBtn;
        private Button HiddenBraveBtn;
        private Button HiddenFirefoxBtn;
        private Button HiddenChromeBtn;
        private CheckBox CloneBrowserCheckbox;
        private Guna2Button ExtraBtn;
        private Guna2ContextMenuStrip hVNCContextMenuStrip;
        private ToolStripMenuItem ResetAllWindowsToolStripMenuItem;
    }
}
