using System;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Text;
using System.Windows.Forms;
using ComponentFactory.Krypton.Toolkit;
using Guna.UI2.WinForms;
using InvokedServer.Controls;
using InvokedServer.Properties;

namespace InvokedServer.Forms
{
    partial class FrmRemoteWebcam
    {
        private IContainer components;

        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null)
                this.components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = (IContainer)new System.ComponentModel.Container();
            ComponentResourceManager resources = new ComponentResourceManager(typeof(FrmRemoteWebcam));
            this.cbResolutions = new Guna2ComboBox();
            this.RDExtra = new Guna2GradientButton();
            this.lblQualityShow = new Label();
            this.lblQuality = new Label();
            this.SizeLabel = new Label();
            this.cbWebcams = new Guna2ComboBox();
            this.btnStop = new Guna2GradientButton();
            this.btnHide = new Guna2GradientButton();
            this.btnStart = new Guna2GradientButton();
            this.btnShow = new Guna2GradientButton();
            this.panelTop = new Panel();
            this.barQuality = new KryptonTrackBar();
            this.TrackBarPalette = new KryptonPalette(this.components);
            this.ExtrasContextMenuStrip = new Guna2ContextMenuStrip();
            this.ScreenshotToolStripMenuItem = new ToolStripMenuItem();
            this.picWebcam = new RapidPictureBox();
            this.PluginLabel = new Label();
            this.panelTop.SuspendLayout();
            this.ExtrasContextMenuStrip.SuspendLayout();
            ((ISupportInitialize)this.picWebcam).BeginInit();
            this.SuspendLayout();
            this.cbResolutions.BackColor = Color.Transparent;
            this.cbResolutions.BorderColor = Color.FromArgb(72, 82, 98);
            this.cbResolutions.BorderRadius = 2;
            this.cbResolutions.DrawMode = DrawMode.OwnerDrawFixed;
            this.cbResolutions.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cbResolutions.Enabled = false;
            this.cbResolutions.FillColor = Color.FromArgb(48, 51, 66);
            this.cbResolutions.FocusedColor = Color.Empty;
            this.cbResolutions.Font = new Font("Segoe UI", 8.25f);
            this.cbResolutions.ForeColor = Color.White;
            this.cbResolutions.ItemHeight = 18;
            this.cbResolutions.Items.AddRange(new object[1]
            {
        (object) "N/A"
            });
            this.cbResolutions.Location = new Point(303, 4);
            this.cbResolutions.Margin = new Padding(0);
            this.cbResolutions.Name = "cbResolutions";
            this.cbResolutions.Size = new Size(142, 24);
            this.cbResolutions.TabIndex = 45;
            this.RDExtra.Animated = true;
            this.RDExtra.BackColor = Color.FromArgb(62, 72, 88);
            this.RDExtra.BorderColor = Color.FromArgb(72, 82, 98);
            this.RDExtra.BorderRadius = 2;
            this.RDExtra.BorderThickness = 1;
            this.RDExtra.DisabledState.BorderColor = Color.DarkGray;
            this.RDExtra.DisabledState.CustomBorderColor = Color.DarkGray;
            this.RDExtra.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.RDExtra.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.RDExtra.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.RDExtra.FillColor = Color.FromArgb(35, 35, 35);
            this.RDExtra.FillColor2 = Color.FromArgb(62, 72, 88);
            this.RDExtra.Font = new Font("Segoe UI", 8.25f);
            this.RDExtra.ForeColor = Color.White;
            this.RDExtra.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.RDExtra.Image = (Image)Resources.toolbox;
            this.RDExtra.ImageSize = new Size(16, 16);
            this.RDExtra.Location = new Point(5, 29);
            this.RDExtra.Name = "RDExtra";
            this.RDExtra.Size = new Size(68, 23);
            this.RDExtra.TabIndex = 44;
            this.RDExtra.Text = "Extra";
            this.RDExtra.Click += new EventHandler(this.ExtrasBtn_Click);
            this.lblQualityShow.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.lblQualityShow.AutoSize = true;
            this.lblQualityShow.Location = new Point(492, 21);
            this.lblQualityShow.Name = "lblQualityShow";
            this.lblQualityShow.Size = new Size(44, 13);
            this.lblQualityShow.TabIndex = 43;
            this.lblQualityShow.Text = "35 (mid)";
            this.lblQuality.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.lblQuality.Location = new Point(479, 4);
            this.lblQuality.Name = "lblQuality";
            this.lblQuality.Size = new Size(69, 15);
            this.lblQuality.TabIndex = 42;
            this.lblQuality.Text = "Quality:";
            this.lblQuality.TextAlign = ContentAlignment.MiddleCenter;
            this.SizeLabel.AutoSize = true;
            this.SizeLabel.Location = new Point(81, 36);
            this.SizeLabel.Name = "SizeLabel";
            this.SizeLabel.Size = new Size(33, 13);
            this.SizeLabel.TabIndex = 39;
            this.SizeLabel.Text = "Size: ";
            this.cbWebcams.BackColor = Color.Transparent;
            this.cbWebcams.BorderColor = Color.FromArgb(72, 82, 98);
            this.cbWebcams.BorderRadius = 2;
            this.cbWebcams.DrawMode = DrawMode.OwnerDrawFixed;
            this.cbWebcams.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cbWebcams.FillColor = Color.FromArgb(48, 51, 66);
            this.cbWebcams.FocusedColor = Color.Empty;
            this.cbWebcams.Font = new Font("Segoe UI", 8.25f);
            this.cbWebcams.ForeColor = Color.White;
            this.cbWebcams.ItemHeight = 18;
            this.cbWebcams.Location = new Point(150, 4);
            this.cbWebcams.Margin = new Padding(0);
            this.cbWebcams.Name = "cbWebcams";
            this.cbWebcams.Size = new Size(142, 24);
            this.cbWebcams.TabIndex = 38;
            this.cbWebcams.SelectedIndexChanged += new EventHandler(this.cbWebcams_SelectedIndexChanged);
            this.btnStop.Animated = true;
            this.btnStop.BorderColor = Color.FromArgb(200, 0, 0);
            this.btnStop.BorderRadius = 2;
            this.btnStop.BorderThickness = 1;
            this.btnStop.DisabledState.BorderColor = Color.DarkGray;
            this.btnStop.DisabledState.CustomBorderColor = Color.DarkGray;
            this.btnStop.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.btnStop.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.btnStop.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.btnStop.Enabled = false;
            this.btnStop.FillColor = Color.FromArgb(35, 35, 35);
            this.btnStop.FillColor2 = Color.FromArgb(100, 35, 35);
            this.btnStop.Font = new Font("Segoe UI", 8.25f);
            this.btnStop.ForeColor = Color.FromArgb(250, 0, 0);
            this.btnStop.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.btnStop.Location = new Point(79, 4);
            this.btnStop.Name = "btnStop";
            this.btnStop.Size = new Size(68, 23);
            this.btnStop.TabIndex = 33;
            this.btnStop.Text = "Stop";
            this.btnStop.Click += new EventHandler(this.btnStop_Click);
            this.btnHide.Animated = true;
            this.btnHide.BackColor = Color.FromArgb(62, 72, 88);
            this.btnHide.BorderColor = Color.FromArgb(72, 82, 98);
            this.btnHide.BorderRadius = 2;
            this.btnHide.BorderThickness = 1;
            this.btnHide.DisabledState.BorderColor = Color.DarkGray;
            this.btnHide.DisabledState.CustomBorderColor = Color.DarkGray;
            this.btnHide.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.btnHide.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.btnHide.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.btnHide.FillColor = Color.FromArgb(35, 35, 35);
            this.btnHide.FillColor2 = Color.FromArgb(62, 72, 88);
            this.btnHide.Font = new Font("Segoe UI", 8.25f);
            this.btnHide.ForeColor = Color.White;
            this.btnHide.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.btnHide.Image = (Image)Resources.arrow_up;
            this.btnHide.ImageSize = new Size(16, 16);
            this.btnHide.Location = new Point(259, 35);
            this.btnHide.Name = "btnHide";
            this.btnHide.Size = new Size(70, 19);
            this.btnHide.TabIndex = 32;
            this.btnHide.Text = "Hide";
            this.btnHide.Click += new EventHandler(this.btnHide_Click);
            this.btnStart.Animated = true;
            this.btnStart.BorderColor = Color.FromArgb(0, 200, 0);
            this.btnStart.BorderRadius = 2;
            this.btnStart.BorderThickness = 1;
            this.btnStart.DisabledState.BorderColor = Color.DarkGray;
            this.btnStart.DisabledState.CustomBorderColor = Color.DarkGray;
            this.btnStart.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.btnStart.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.btnStart.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.btnStart.FillColor = Color.FromArgb(35, 35, 35);
            this.btnStart.FillColor2 = Color.FromArgb(35, 100, 35);
            this.btnStart.Font = new Font("Segoe UI", 8.25f);
            this.btnStart.ForeColor = Color.FromArgb(0, 250, 0);
            this.btnStart.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.btnStart.Location = new Point(5, 4);
            this.btnStart.Name = "btnStart";
            this.btnStart.Size = new Size(68, 23);
            this.btnStart.TabIndex = 27;
            this.btnStart.Text = "Start";
            this.btnStart.Click += new EventHandler(this.btnStart_Click);
            this.btnShow.Animated = true;
            this.btnShow.BackColor = Color.FromArgb(62, 72, 88);
            this.btnShow.BorderColor = Color.FromArgb(72, 82, 98);
            this.btnShow.BorderRadius = 2;
            this.btnShow.BorderThickness = 1;
            this.btnShow.DisabledState.BorderColor = Color.DarkGray;
            this.btnShow.DisabledState.CustomBorderColor = Color.DarkGray;
            this.btnShow.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.btnShow.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.btnShow.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.btnShow.FillColor = Color.FromArgb(35, 35, 35);
            this.btnShow.FillColor2 = Color.FromArgb(62, 72, 88);
            this.btnShow.Font = new Font("Segoe UI", 8.25f);
            this.btnShow.ForeColor = Color.White;
            this.btnShow.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.btnShow.Image = (Image)Resources.arrow_down;
            this.btnShow.ImageSize = new Size(16, 16);
            this.btnShow.Location = new Point(0, 0);
            this.btnShow.Name = "btnShow";
            this.btnShow.Size = new Size(70, 19);
            this.btnShow.TabIndex = 40;
            this.btnShow.Text = "Show";
            this.btnShow.Visible = false;
            this.btnShow.Click += new EventHandler(this.btnShow_Click);
            this.panelTop.BackColor = Color.FromArgb(58, 61, 76);
            this.panelTop.Controls.Add((Control)this.barQuality);
            this.panelTop.Controls.Add((Control)this.RDExtra);
            this.panelTop.Controls.Add((Control)this.lblQualityShow);
            this.panelTop.Controls.Add((Control)this.cbResolutions);
            this.panelTop.Controls.Add((Control)this.btnStart);
            this.panelTop.Controls.Add((Control)this.btnHide);
            this.panelTop.Controls.Add((Control)this.btnStop);
            this.panelTop.Controls.Add((Control)this.cbWebcams);
            this.panelTop.Controls.Add((Control)this.lblQuality);
            this.panelTop.Controls.Add((Control)this.SizeLabel);
            this.panelTop.Dock = DockStyle.Top;
            this.panelTop.ForeColor = Color.White;
            this.panelTop.Location = new Point(0, 0);
            this.panelTop.Name = "panelTop";
            this.panelTop.Size = new Size(624, 55);
            this.panelTop.TabIndex = 41;
            this.barQuality.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.barQuality.CausesValidation = false;
            this.barQuality.DrawBackground = true;
            this.barQuality.Location = new Point(542, 4);
            this.barQuality.Maximum = 100;
            this.barQuality.Minimum = 1;
            this.barQuality.Name = "barQuality";
            this.barQuality.Palette = (IPalette)this.TrackBarPalette;
            this.barQuality.PaletteMode = PaletteMode.Custom;
            this.barQuality.Size = new Size(70, 27);
            this.barQuality.TabIndex = 42;
            this.barQuality.TabStop = false;
            this.barQuality.TickStyle = TickStyle.TopLeft;
            this.barQuality.Value = 35;
            this.barQuality.Scroll += new EventHandler(this.barQuality_Scroll);
            this.TrackBarPalette.BasePaletteMode = PaletteMode.Global;
            this.TrackBarPalette.Common.StateCommon.Back.Color1 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.Common.StateCommon.Back.Color2 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.FormStyles.FormCommon.StateActive.Back.Color1 = Color.FromArgb((int)byte.MaxValue, (int)byte.MaxValue, 192);
            this.TrackBarPalette.FormStyles.FormCommon.StateActive.Back.Color2 = Color.FromArgb((int)byte.MaxValue, 192, (int)byte.MaxValue);
            this.TrackBarPalette.FormStyles.FormCommon.StateCommon.Back.Color1 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.FormStyles.FormCommon.StateCommon.Back.Color2 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.FormStyles.FormCustom1.StateCommon.Back.Color1 = Color.FromArgb(192, (int)byte.MaxValue, (int)byte.MaxValue);
            this.TrackBarPalette.FormStyles.FormCustom1.StateCommon.Back.Color2 = Color.Red;
            this.TrackBarPalette.TrackBar.OverrideFocus.Tick.Color1 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.OverrideFocus.Tick.Color2 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.OverrideFocus.Tick.Color3 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.OverrideFocus.Tick.Color4 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.OverrideFocus.Tick.Color5 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.StateCommon.Position.Color1 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Position.Color2 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Position.Color3 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.StateCommon.Position.Color4 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.StateCommon.Position.Color5 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.StateCommon.Tick.Color1 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Tick.Color2 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Tick.Color3 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Tick.Color4 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Tick.Color5 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Track.Color1 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Track.Color2 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Track.Color3 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Track.Color4 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Track.Color5 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateNormal.Tick.Color1 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateNormal.Tick.Color2 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateNormal.Tick.Color3 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.StateNormal.Tick.Color4 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.StateNormal.Tick.Color5 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.StatePressed.Position.Color1 = Color.FromArgb(151, 164, 227);
            this.TrackBarPalette.TrackBar.StatePressed.Position.Color2 = Color.FromArgb(151, 164, 227);
            this.TrackBarPalette.TrackBar.StatePressed.Position.Color3 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StatePressed.Position.Color4 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StatePressed.Position.Color5 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateTracking.Position.Color1 = Color.FromArgb(151, 164, 227);
            this.TrackBarPalette.TrackBar.StateTracking.Position.Color2 = Color.FromArgb(151, 164, 227);
            this.TrackBarPalette.TrackBar.StateTracking.Position.Color3 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateTracking.Position.Color4 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateTracking.Position.Color5 = Color.FromArgb(92, 102, 118);
            this.ExtrasContextMenuStrip.Items.AddRange(new ToolStripItem[1]
            {
        (ToolStripItem) this.ScreenshotToolStripMenuItem
            });
            this.ExtrasContextMenuStrip.Name = "hVNCContextMenuStrip";
            this.ExtrasContextMenuStrip.RenderStyle.ArrowColor = Color.FromArgb(151, 143, (int)byte.MaxValue);
            this.ExtrasContextMenuStrip.RenderStyle.BorderColor = Color.Gainsboro;
            this.ExtrasContextMenuStrip.RenderStyle.ColorTable = (ProfessionalColorTable)null;
            this.ExtrasContextMenuStrip.RenderStyle.RoundedEdges = true;
            this.ExtrasContextMenuStrip.RenderStyle.SelectionArrowColor = Color.White;
            this.ExtrasContextMenuStrip.RenderStyle.SelectionBackColor = Color.FromArgb(100, 88, (int)byte.MaxValue);
            this.ExtrasContextMenuStrip.RenderStyle.SelectionForeColor = Color.White;
            this.ExtrasContextMenuStrip.RenderStyle.SeparatorColor = Color.Gainsboro;
            this.ExtrasContextMenuStrip.RenderStyle.TextRenderingHint = TextRenderingHint.SystemDefault;
            this.ExtrasContextMenuStrip.Size = new Size(133, 26);
            this.ScreenshotToolStripMenuItem.BackColor = Color.FromArgb(58, 61, 76);
            this.ScreenshotToolStripMenuItem.ForeColor = Color.White;
            this.ScreenshotToolStripMenuItem.Image = (Image)Resources.camera;
            this.ScreenshotToolStripMenuItem.Name = "ScreenshotToolStripMenuItem";
            this.ScreenshotToolStripMenuItem.Size = new Size(132, 22);
            this.ScreenshotToolStripMenuItem.Text = "Screenshot";
            this.picWebcam.BackColor = Color.Black;
            this.picWebcam.Cursor = Cursors.Default;
            this.picWebcam.Dock = DockStyle.Fill;
            this.picWebcam.GetImageSafe = (Image)null;
            this.picWebcam.Location = new Point(0, 55);
            this.picWebcam.Name = "picWebcam";
            this.picWebcam.Running = false;
            this.picWebcam.Size = new Size(624, 386);
            this.picWebcam.SizeMode = PictureBoxSizeMode.AutoSize;
            this.picWebcam.TabIndex = 1;
            this.picWebcam.TabStop = false;
            this.PluginLabel.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.PluginLabel.AutoSize = true;
            this.PluginLabel.BackColor = Color.Black;
            this.PluginLabel.ForeColor = Color.OrangeRed;
            this.PluginLabel.Location = new Point(234, 75);
            this.PluginLabel.Name = "PluginLabel";
            this.PluginLabel.Size = new Size(152, 13);
            this.PluginLabel.TabIndex = 42;
            this.PluginLabel.Text = "Checking if Module is loaded...";
            this.AutoScaleDimensions = new SizeF(96f, 96f);
            this.AutoScaleMode = AutoScaleMode.Dpi;
            this.ClientSize = new Size(624, 441);
            this.Controls.Add((Control)this.PluginLabel);
            this.Controls.Add((Control)this.btnShow);
            this.Controls.Add((Control)this.picWebcam);
            this.Controls.Add((Control)this.panelTop);
            this.Icon = (Icon)resources.GetObject("$this.Icon");
            this.MinimumSize = new Size(480, 375);
            this.Name = "FrmRemoteWebcam";
            this.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "FrmRemoteWebcam []";
            this.FormClosing += new FormClosingEventHandler(this.FrmRemoteWebcam_FormClosing);
            this.Load += new EventHandler(this.FrmRemoteWebcam_Load);
            this.Resize += new EventHandler(this.FrmRemoteWebcam_Resize);
            this.panelTop.ResumeLayout(false);
            this.panelTop.PerformLayout();
            this.ExtrasContextMenuStrip.ResumeLayout(false);
            ((ISupportInitialize)this.picWebcam).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private RapidPictureBox picWebcam;
        private Label SizeLabel;
        private Guna2ComboBox cbWebcams;
        private Guna2GradientButton btnStop;
        private Guna2GradientButton btnHide;
        private Guna2GradientButton btnStart;
        private Guna2GradientButton btnShow;
        private Label lblQualityShow;
        private Label lblQuality;
        private Guna2GradientButton RDExtra;
        private Guna2ComboBox cbResolutions;
        private Panel panelTop;
        private Guna2ContextMenuStrip ExtrasContextMenuStrip;
        private ToolStripMenuItem ScreenshotToolStripMenuItem;
        private KryptonTrackBar barQuality;
        private KryptonPalette TrackBarPalette;
        private Label PluginLabel;
    }
}
