using System;
using System.ComponentModel;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Text;
using System.Windows.Forms;
using ComponentFactory.Krypton.Toolkit;
using Guna.UI2.WinForms;
using InvokedServer.Controls;
using InvokedServer.Properties;

namespace InvokedServer.Forms
{
    partial class FrmRemoteDesktop
    {
        private IContainer components;

        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null)
                this.components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = (IContainer)new System.ComponentModel.Container();
            ComponentResourceManager resources = new ComponentResourceManager(typeof(FrmRemoteDesktop));
            this.toolTipButtons = new ToolTip(this.components);
            this.btnKeyboard = new Guna2GradientButton();
            this.btnMouse = new Guna2GradientButton();
            this.BtnMouseMovement = new Guna2GradientButton();
            this.panelTop = new Guna2GradientPanel();
            this.barQuality = new KryptonTrackBar();
            this.TrackBarPalette = new KryptonPalette(this.components);
            this.SizeLabel = new Label();
            this.cbMonitors = new Guna2ComboBox();
            this.btnStop = new Guna2GradientButton();
            this.RDExtra = new Guna2GradientButton();
            this.lblQualityShow = new Label();
            this.btnStart = new Guna2GradientButton();
            this.lblQuality = new Label();
            this.btnShow = new Guna2GradientButton();
            this.RDcontextMenuStrip = new Guna2ContextMenuStrip();
            this.ShowCursorBtn = new ToolStripMenuItem();
            this.CapFPSToolStripMenuItem = new ToolStripMenuItem();
            this.fullScreenToolStripMenuItem = new ToolStripMenuItem();
            this.btnHide = new ToolStripMenuItem();
            this.btnExit = new Guna2GradientButton();
            this.PluginLabel = new Label();
            this.picDesktop = new RapidPictureBox();
            this.OldGraphicsEngineToolStripMenuItem = new ToolStripMenuItem();
            this.panelTop.SuspendLayout();
            this.RDcontextMenuStrip.SuspendLayout();
            ((ISupportInitialize)this.picDesktop).BeginInit();
            this.SuspendLayout();
            this.btnKeyboard.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.btnKeyboard.Animated = true;
            this.btnKeyboard.BackColor = Color.FromArgb(62, 72, 88);
            this.btnKeyboard.BorderColor = Color.FromArgb(72, 82, 98);
            this.btnKeyboard.BorderRadius = 2;
            this.btnKeyboard.BorderThickness = 1;
            this.btnKeyboard.DisabledState.BorderColor = Color.DarkGray;
            this.btnKeyboard.DisabledState.CustomBorderColor = Color.DarkGray;
            this.btnKeyboard.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.btnKeyboard.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.btnKeyboard.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.btnKeyboard.FillColor = Color.FromArgb(35, 35, 35);
            this.btnKeyboard.FillColor2 = Color.FromArgb(62, 72, 88);
            this.btnKeyboard.Font = new Font("Segoe UI", 8.25f);
            this.btnKeyboard.ForeColor = Color.White;
            this.btnKeyboard.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.btnKeyboard.Image = (Image)Resources.keyboard_delete;
            this.btnKeyboard.ImageSize = new Size(16, 16);
            this.btnKeyboard.Location = new Point(442, 5);
            this.btnKeyboard.Name = "btnKeyboard";
            this.btnKeyboard.Size = new Size(28, 28);
            this.btnKeyboard.TabIndex = 35;
            this.btnKeyboard.TabStop = false;
            this.toolTipButtons.SetToolTip((Control)this.btnKeyboard, "Enable keyboard input.");
            this.btnKeyboard.Click += new EventHandler(this.btnKeyboard_Click);
            this.btnMouse.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.btnMouse.Animated = true;
            this.btnMouse.BackColor = Color.FromArgb(62, 72, 88);
            this.btnMouse.BorderColor = Color.FromArgb(72, 82, 98);
            this.btnMouse.BorderRadius = 2;
            this.btnMouse.BorderThickness = 1;
            this.btnMouse.DisabledState.BorderColor = Color.DarkGray;
            this.btnMouse.DisabledState.CustomBorderColor = Color.DarkGray;
            this.btnMouse.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.btnMouse.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.btnMouse.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.btnMouse.FillColor = Color.FromArgb(35, 35, 35);
            this.btnMouse.FillColor2 = Color.FromArgb(62, 72, 88);
            this.btnMouse.Font = new Font("Segoe UI", 8.25f);
            this.btnMouse.ForeColor = Color.White;
            this.btnMouse.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.btnMouse.Image = (Image)Resources.mouse_delete;
            this.btnMouse.ImageSize = new Size(16, 16);
            this.btnMouse.Location = new Point(476, 5);
            this.btnMouse.Name = "btnMouse";
            this.btnMouse.Size = new Size(28, 28);
            this.btnMouse.TabIndex = 34;
            this.btnMouse.TabStop = false;
            this.toolTipButtons.SetToolTip((Control)this.btnMouse, "Enable mouse input.");
            this.btnMouse.Click += new EventHandler(this.btnMouse_Click);
            this.BtnMouseMovement.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.BtnMouseMovement.Animated = true;
            this.BtnMouseMovement.BackColor = Color.FromArgb(62, 72, 88);
            this.BtnMouseMovement.BorderColor = Color.FromArgb(72, 82, 98);
            this.BtnMouseMovement.BorderRadius = 2;
            this.BtnMouseMovement.BorderThickness = 1;
            this.BtnMouseMovement.DisabledState.BorderColor = Color.DarkGray;
            this.BtnMouseMovement.DisabledState.CustomBorderColor = Color.DarkGray;
            this.BtnMouseMovement.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.BtnMouseMovement.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.BtnMouseMovement.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.BtnMouseMovement.Enabled = false;
            this.BtnMouseMovement.FillColor = Color.FromArgb(35, 35, 35);
            this.BtnMouseMovement.FillColor2 = Color.FromArgb(62, 72, 88);
            this.BtnMouseMovement.Font = new Font("Segoe UI", 8.25f);
            this.BtnMouseMovement.ForeColor = Color.White;
            this.BtnMouseMovement.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.BtnMouseMovement.Image = (Image)Resources.MouseDisableMovement;
            this.BtnMouseMovement.ImageSize = new Size(16, 16);
            this.BtnMouseMovement.Location = new Point(510, 5);
            this.BtnMouseMovement.Name = "BtnMouseMovement";
            this.BtnMouseMovement.Size = new Size(28, 28);
            this.BtnMouseMovement.TabIndex = 37;
            this.BtnMouseMovement.TabStop = false;
            this.toolTipButtons.SetToolTip((Control)this.BtnMouseMovement, "Enable mouse movement.");
            this.BtnMouseMovement.Click += new EventHandler(this.BtnMouseMovement_Click);
            this.panelTop.BackColor = Color.FromArgb(58, 61, 76);
            this.panelTop.BorderColor = Color.FromArgb((int)byte.MaxValue, 128, 128);
            this.panelTop.Controls.Add((Control)this.barQuality);
            this.panelTop.Controls.Add((Control)this.SizeLabel);
            this.panelTop.Controls.Add((Control)this.cbMonitors);
            this.panelTop.Controls.Add((Control)this.BtnMouseMovement);
            this.panelTop.Controls.Add((Control)this.btnKeyboard);
            this.panelTop.Controls.Add((Control)this.btnMouse);
            this.panelTop.Controls.Add((Control)this.btnStop);
            this.panelTop.Controls.Add((Control)this.RDExtra);
            this.panelTop.Controls.Add((Control)this.lblQualityShow);
            this.panelTop.Controls.Add((Control)this.btnStart);
            this.panelTop.Controls.Add((Control)this.lblQuality);
            this.panelTop.Dock = DockStyle.Top;
            this.panelTop.ForeColor = Color.White;
            this.panelTop.Location = new Point(0, 0);
            this.panelTop.Name = "panelTop";
            this.panelTop.Size = new Size(624, 36);
            this.panelTop.TabIndex = 11;
            this.barQuality.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.barQuality.CausesValidation = false;
            this.barQuality.DrawBackground = true;
            this.barQuality.Location = new Point(366, 3);
            this.barQuality.Maximum = 100;
            this.barQuality.Minimum = 1;
            this.barQuality.Name = "barQuality";
            this.barQuality.Palette = (IPalette)this.TrackBarPalette;
            this.barQuality.PaletteMode = PaletteMode.Custom;
            this.barQuality.Size = new Size(70, 27);
            this.barQuality.TabIndex = 40;
            this.barQuality.TabStop = false;
            this.barQuality.TickStyle = TickStyle.TopLeft;
            this.barQuality.Value = 35;
            this.barQuality.Scroll += new EventHandler(this.barQuality_Scroll);
            this.TrackBarPalette.BasePaletteMode = PaletteMode.Global;
            this.TrackBarPalette.Common.StateCommon.Back.Color1 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.Common.StateCommon.Back.Color2 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.FormStyles.FormCommon.StateActive.Back.Color1 = Color.FromArgb((int)byte.MaxValue, (int)byte.MaxValue, 192);
            this.TrackBarPalette.FormStyles.FormCommon.StateActive.Back.Color2 = Color.FromArgb((int)byte.MaxValue, 192, (int)byte.MaxValue);
            this.TrackBarPalette.FormStyles.FormCommon.StateCommon.Back.Color1 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.FormStyles.FormCommon.StateCommon.Back.Color2 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.FormStyles.FormCustom1.StateCommon.Back.Color1 = Color.FromArgb(192, (int)byte.MaxValue, (int)byte.MaxValue);
            this.TrackBarPalette.FormStyles.FormCustom1.StateCommon.Back.Color2 = Color.Red;
            this.TrackBarPalette.TrackBar.OverrideFocus.Tick.Color1 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.OverrideFocus.Tick.Color2 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.OverrideFocus.Tick.Color3 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.OverrideFocus.Tick.Color4 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.OverrideFocus.Tick.Color5 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.StateCommon.Position.Color1 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Position.Color2 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Position.Color3 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.StateCommon.Position.Color4 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.StateCommon.Position.Color5 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.StateCommon.Tick.Color1 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Tick.Color2 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Tick.Color3 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Tick.Color4 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Tick.Color5 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Track.Color1 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Track.Color2 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Track.Color3 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Track.Color4 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateCommon.Track.Color5 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateNormal.Tick.Color1 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateNormal.Tick.Color2 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateNormal.Tick.Color3 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.StateNormal.Tick.Color4 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.StateNormal.Tick.Color5 = Color.FromArgb(58, 61, 76);
            this.TrackBarPalette.TrackBar.StatePressed.Position.Color1 = Color.FromArgb(151, 164, 227);
            this.TrackBarPalette.TrackBar.StatePressed.Position.Color2 = Color.FromArgb(151, 164, 227);
            this.TrackBarPalette.TrackBar.StatePressed.Position.Color3 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StatePressed.Position.Color4 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StatePressed.Position.Color5 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateTracking.Position.Color1 = Color.FromArgb(151, 164, 227);
            this.TrackBarPalette.TrackBar.StateTracking.Position.Color2 = Color.FromArgb(151, 164, 227);
            this.TrackBarPalette.TrackBar.StateTracking.Position.Color3 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateTracking.Position.Color4 = Color.FromArgb(92, 102, 118);
            this.TrackBarPalette.TrackBar.StateTracking.Position.Color5 = Color.FromArgb(92, 102, 118);
            this.SizeLabel.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.SizeLabel.AutoSize = true;
            this.SizeLabel.Location = new Point(544, -1);
            this.SizeLabel.Margin = new Padding(0);
            this.SizeLabel.Name = "SizeLabel";
            this.SizeLabel.Size = new Size(33, 13);
            this.SizeLabel.TabIndex = 39;
            this.SizeLabel.Text = "Size: ";
            this.cbMonitors.BackColor = Color.Transparent;
            this.cbMonitors.BorderColor = Color.FromArgb(72, 82, 98);
            this.cbMonitors.BorderRadius = 2;
            this.cbMonitors.DrawMode = DrawMode.OwnerDrawFixed;
            this.cbMonitors.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cbMonitors.FillColor = Color.FromArgb(48, 51, 66);
            this.cbMonitors.FocusedColor = Color.Empty;
            this.cbMonitors.Font = new Font("Segoe UI", 8.25f);
            this.cbMonitors.ForeColor = Color.White;
            this.cbMonitors.ItemHeight = 18;
            this.cbMonitors.Location = new Point(167, 5);
            this.cbMonitors.Margin = new Padding(0);
            this.cbMonitors.Name = "cbMonitors";
            this.cbMonitors.Size = new Size(142, 24);
            this.cbMonitors.TabIndex = 38;
            this.btnStop.Animated = true;
            this.btnStop.BorderColor = Color.FromArgb(200, 0, 0);
            this.btnStop.BorderRadius = 2;
            this.btnStop.BorderThickness = 1;
            this.btnStop.DisabledState.BorderColor = Color.DarkGray;
            this.btnStop.DisabledState.CustomBorderColor = Color.DarkGray;
            this.btnStop.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.btnStop.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.btnStop.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.btnStop.Enabled = false;
            this.btnStop.FillColor = Color.FromArgb(35, 35, 35);
            this.btnStop.FillColor2 = Color.FromArgb(100, 35, 35);
            this.btnStop.Font = new Font("Segoe UI", 8.25f);
            this.btnStop.ForeColor = Color.FromArgb(250, 0, 0);
            this.btnStop.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.btnStop.Location = new Point(86, 5);
            this.btnStop.Name = "btnStop";
            this.btnStop.Size = new Size(68, 23);
            this.btnStop.TabIndex = 33;
            this.btnStop.Text = "Stop";
            this.btnStop.Click += new EventHandler(this.btnStop_Click);
            this.RDExtra.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.RDExtra.Animated = true;
            this.RDExtra.BackColor = Color.FromArgb(62, 72, 88);
            this.RDExtra.BorderColor = Color.FromArgb(72, 82, 98);
            this.RDExtra.BorderRadius = 2;
            this.RDExtra.BorderThickness = 1;
            this.RDExtra.DisabledState.BorderColor = Color.DarkGray;
            this.RDExtra.DisabledState.CustomBorderColor = Color.DarkGray;
            this.RDExtra.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.RDExtra.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.RDExtra.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.RDExtra.FillColor = Color.FromArgb(35, 35, 35);
            this.RDExtra.FillColor2 = Color.FromArgb(62, 72, 88);
            this.RDExtra.Font = new Font("Segoe UI", 8.25f);
            this.RDExtra.ForeColor = Color.White;
            this.RDExtra.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.RDExtra.Image = (Image)Resources.toolbox;
            this.RDExtra.ImageSize = new Size(16, 16);
            this.RDExtra.Location = new Point(541, 13);
            this.RDExtra.Name = "RDExtra";
            this.RDExtra.Size = new Size(70, 23);
            this.RDExtra.TabIndex = 30;
            this.RDExtra.Text = "Extra";
            this.RDExtra.Click += new EventHandler(this.RDExtra_Click);
            this.lblQualityShow.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.lblQualityShow.AutoSize = true;
            this.lblQualityShow.Location = new Point(314, 20);
            this.lblQualityShow.Name = "lblQualityShow";
            this.lblQualityShow.Size = new Size(47, 13);
            this.lblQualityShow.TabIndex = 5;
            this.lblQualityShow.Text = "35 (mid)";
            this.btnStart.Animated = true;
            this.btnStart.BorderColor = Color.FromArgb(0, 200, 0);
            this.btnStart.BorderRadius = 2;
            this.btnStart.BorderThickness = 1;
            this.btnStart.DisabledState.BorderColor = Color.DarkGray;
            this.btnStart.DisabledState.CustomBorderColor = Color.DarkGray;
            this.btnStart.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.btnStart.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.btnStart.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.btnStart.FillColor = Color.FromArgb(35, 35, 35);
            this.btnStart.FillColor2 = Color.FromArgb(35, 100, 35);
            this.btnStart.Font = new Font("Segoe UI", 8.25f);
            this.btnStart.ForeColor = Color.FromArgb(0, 250, 0);
            this.btnStart.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.btnStart.Location = new Point(12, 5);
            this.btnStart.Name = "btnStart";
            this.btnStart.Size = new Size(68, 23);
            this.btnStart.TabIndex = 27;
            this.btnStart.Text = "Start";
            this.btnStart.Click += new EventHandler(this.btnStart_Click);
            this.lblQuality.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.lblQuality.AutoSize = true;
            this.lblQuality.Location = new Point(314, 4);
            this.lblQuality.Name = "lblQuality";
            this.lblQuality.Size = new Size(46, 13);
            this.lblQuality.TabIndex = 4;
            this.lblQuality.Text = "Quality:";
            this.btnShow.Animated = true;
            this.btnShow.BackColor = Color.FromArgb(62, 72, 88);
            this.btnShow.BorderColor = Color.FromArgb(72, 82, 98);
            this.btnShow.BorderRadius = 2;
            this.btnShow.BorderThickness = 1;
            this.btnShow.DisabledState.BorderColor = Color.DarkGray;
            this.btnShow.DisabledState.CustomBorderColor = Color.DarkGray;
            this.btnShow.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.btnShow.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.btnShow.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.btnShow.FillColor = Color.FromArgb(35, 35, 35);
            this.btnShow.FillColor2 = Color.FromArgb(62, 72, 88);
            this.btnShow.Font = new Font("Segoe UI", 8.25f);
            this.btnShow.ForeColor = Color.White;
            this.btnShow.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.btnShow.Image = (Image)Resources.arrow_down;
            this.btnShow.ImageSize = new Size(16, 16);
            this.btnShow.Location = new Point(0, 0);
            this.btnShow.Name = "btnShow";
            this.btnShow.Size = new Size(70, 19);
            this.btnShow.TabIndex = 39;
            this.btnShow.Text = "Show";
            this.btnShow.Visible = false;
            this.btnShow.Click += new EventHandler(this.btnShow_Click);
            this.RDcontextMenuStrip.Items.AddRange(new ToolStripItem[5]
            {
        (ToolStripItem) this.ShowCursorBtn,
        (ToolStripItem) this.OldGraphicsEngineToolStripMenuItem,
        (ToolStripItem) this.CapFPSToolStripMenuItem,
        (ToolStripItem) this.fullScreenToolStripMenuItem,
        (ToolStripItem) this.btnHide
            });
            this.RDcontextMenuStrip.Name = "hVNCContextMenuStrip";
            this.RDcontextMenuStrip.RenderStyle.ArrowColor = Color.FromArgb(151, 143, (int)byte.MaxValue);
            this.RDcontextMenuStrip.RenderStyle.BorderColor = Color.Gainsboro;
            this.RDcontextMenuStrip.RenderStyle.ColorTable = (ProfessionalColorTable)null;
            this.RDcontextMenuStrip.RenderStyle.RoundedEdges = true;
            this.RDcontextMenuStrip.RenderStyle.SelectionArrowColor = Color.White;
            this.RDcontextMenuStrip.RenderStyle.SelectionBackColor = Color.FromArgb(100, 88, (int)byte.MaxValue);
            this.RDcontextMenuStrip.RenderStyle.SelectionForeColor = Color.White;
            this.RDcontextMenuStrip.RenderStyle.SeparatorColor = Color.Gainsboro;
            this.RDcontextMenuStrip.RenderStyle.TextRenderingHint = TextRenderingHint.SystemDefault;
            this.RDcontextMenuStrip.Size = new Size(220, 136);
            this.ShowCursorBtn.BackColor = Color.FromArgb(58, 61, 76);
            this.ShowCursorBtn.Checked = true;
            this.ShowCursorBtn.CheckOnClick = true;
            this.ShowCursorBtn.CheckState = CheckState.Checked;
            this.ShowCursorBtn.ForeColor = Color.White;
            this.ShowCursorBtn.Name = "ShowCursorBtn";
            this.ShowCursorBtn.Size = new Size(219, 22);
            this.ShowCursorBtn.Text = "Show Cursor";
            this.ShowCursorBtn.Click += new EventHandler(this.ShowCursorBtn_Click);
            this.CapFPSToolStripMenuItem.BackColor = Color.FromArgb(58, 61, 76);
            this.CapFPSToolStripMenuItem.Checked = true;
            this.CapFPSToolStripMenuItem.CheckOnClick = true;
            this.CapFPSToolStripMenuItem.CheckState = CheckState.Checked;
            this.CapFPSToolStripMenuItem.ForeColor = Color.White;
            this.CapFPSToolStripMenuItem.Name = "CapFPSToolStripMenuItem";
            this.CapFPSToolStripMenuItem.Size = new Size(219, 22);
            this.CapFPSToolStripMenuItem.Text = "Cap FPS";
            this.CapFPSToolStripMenuItem.Click += new EventHandler(this.CapFPSToolStripMenuItem_Click);
            this.fullScreenToolStripMenuItem.BackColor = Color.FromArgb(58, 61, 76);
            this.fullScreenToolStripMenuItem.ForeColor = Color.White;
            this.fullScreenToolStripMenuItem.Image = (Image)Resources.arrow_inout;
            this.fullScreenToolStripMenuItem.Name = "fullScreenToolStripMenuItem";
            this.fullScreenToolStripMenuItem.Size = new Size(219, 22);
            this.fullScreenToolStripMenuItem.Text = "Full screen";
            this.fullScreenToolStripMenuItem.Click += new EventHandler(this.fullScreenToolStripMenuItem_Click);
            this.btnHide.BackColor = Color.FromArgb(58, 61, 76);
            this.btnHide.ForeColor = Color.White;
            this.btnHide.Image = (Image)Resources.arrow_up;
            this.btnHide.Name = "btnHide";
            this.btnHide.Size = new Size(219, 22);
            this.btnHide.Text = "Hide";
            this.btnHide.Click += new EventHandler(this.hideToolStripMenuItem_Click);
            this.btnExit.Animated = true;
            this.btnExit.BackColor = Color.FromArgb(62, 72, 88);
            this.btnExit.BorderColor = Color.FromArgb(72, 82, 98);
            this.btnExit.BorderRadius = 2;
            this.btnExit.BorderThickness = 1;
            this.btnExit.DisabledState.BorderColor = Color.DarkGray;
            this.btnExit.DisabledState.CustomBorderColor = Color.DarkGray;
            this.btnExit.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.btnExit.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.btnExit.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.btnExit.FillColor = Color.FromArgb(35, 35, 35);
            this.btnExit.FillColor2 = Color.FromArgb(62, 72, 88);
            this.btnExit.Font = new Font("Segoe UI", 8.25f);
            this.btnExit.ForeColor = Color.White;
            this.btnExit.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.btnExit.Image = (Image)Resources.arrow_in;
            this.btnExit.ImageSize = new Size(16, 16);
            this.btnExit.Location = new Point(302, 36);
            this.btnExit.Name = "btnExit";
            this.btnExit.Size = new Size(70, 19);
            this.btnExit.TabIndex = 40;
            this.btnExit.Text = "Exit";
            this.btnExit.Visible = false;
            this.btnExit.Click += new EventHandler(this.btnExit_Click);
            this.PluginLabel.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.PluginLabel.AutoSize = true;
            this.PluginLabel.BackColor = Color.Black;
            this.PluginLabel.ForeColor = Color.OrangeRed;
            this.PluginLabel.Location = new Point(254, 58);
            this.PluginLabel.Name = "PluginLabel";
            this.PluginLabel.Size = new Size(167, 13);
            this.PluginLabel.TabIndex = 41;
            this.PluginLabel.Text = "Checking if Module is loaded...";
            this.picDesktop.BackColor = Color.Black;
            this.picDesktop.BorderStyle = BorderStyle.FixedSingle;
            this.picDesktop.CapFPS = false;
            this.picDesktop.Cursor = Cursors.Default;
            this.picDesktop.Dock = DockStyle.Fill;
            this.picDesktop.GetImageSafe = (Image)null;
            this.picDesktop.Location = new Point(0, 36);
            this.picDesktop.Name = "picDesktop";
            this.picDesktop.Running = false;
            this.picDesktop.Size = new Size(624, 405);
            this.picDesktop.SizeMode = PictureBoxSizeMode.AutoSize;
            this.picDesktop.TabIndex = 0;
            this.picDesktop.TabStop = false;
            this.picDesktop.MouseDown += new MouseEventHandler(this.picDesktop_MouseDown);
            this.picDesktop.MouseMove += new MouseEventHandler(this.picDesktop_MouseMove);
            this.picDesktop.MouseUp += new MouseEventHandler(this.picDesktop_MouseUp);
            this.OldGraphicsEngineToolStripMenuItem.BackColor = Color.FromArgb(58, 61, 76);
            this.OldGraphicsEngineToolStripMenuItem.CheckOnClick = true;
            this.OldGraphicsEngineToolStripMenuItem.ForeColor = Color.White;
            this.OldGraphicsEngineToolStripMenuItem.Name = "OldGraphicsEngineToolStripMenuItem";
            this.OldGraphicsEngineToolStripMenuItem.Size = new Size(219, 22);
            this.OldGraphicsEngineToolStripMenuItem.Text = "Enable Old Graphics Engine";
            this.OldGraphicsEngineToolStripMenuItem.Click += new EventHandler(this.OldGraphicsEngineToolStripMenuItem_Click);
            this.AutoScaleDimensions = new SizeF(96f, 96f);
            this.AutoScaleMode = AutoScaleMode.Dpi;
            this.ClientSize = new Size(624, 441);
            this.Controls.Add((Control)this.PluginLabel);
            this.Controls.Add((Control)this.btnShow);
            this.Controls.Add((Control)this.btnExit);
            this.Controls.Add((Control)this.picDesktop);
            this.Controls.Add((Control)this.panelTop);
            this.Font = new Font("Segoe UI", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte)0);
            this.Icon = (Icon)resources.GetObject("$this.Icon");
            this.KeyPreview = true;
            this.MinimumSize = new Size(640, 480);
            this.Name = "FrmRemoteDesktop";
            this.StartPosition = FormStartPosition.CenterScreen;
            this.Text = " Remote Desktop";
            this.FormClosing += new FormClosingEventHandler(this.FrmRemoteDesktop_FormClosing);
            this.Load += new EventHandler(this.FrmRemoteDesktop_Load);
            this.Resize += new EventHandler(this.FrmRemoteDesktop_Resize);
            this.panelTop.ResumeLayout(false);
            this.panelTop.PerformLayout();
            this.RDcontextMenuStrip.ResumeLayout(false);
            ((ISupportInitialize)this.picDesktop).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private ToolTip toolTipButtons;
        private RapidPictureBox picDesktop;
        private Guna2GradientPanel panelTop;
        private Guna2ComboBox cbMonitors;
        private Guna2GradientButton BtnMouseMovement;
        private Guna2GradientButton btnKeyboard;
        private Guna2GradientButton btnMouse;
        private Guna2GradientButton btnStop;
        private Guna2GradientButton RDExtra;
        private Label lblQualityShow;
        private Guna2GradientButton btnStart;
        private Label lblQuality;
        private Guna2GradientButton btnShow;
        private Label SizeLabel;
        private KryptonTrackBar barQuality;
        private KryptonPalette TrackBarPalette;
        private Guna2ContextMenuStrip RDcontextMenuStrip;
        private ToolStripMenuItem ShowCursorBtn;
        private ToolStripMenuItem fullScreenToolStripMenuItem;
        private ToolStripMenuItem btnHide;
        private Guna2GradientButton btnExit;
        private Label PluginLabel;
        private ToolStripMenuItem CapFPSToolStripMenuItem;
        private ToolStripMenuItem OldGraphicsEngineToolStripMenuItem;
    }
}
