using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing.Drawing2D;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Guna.UI2.WinForms;

namespace InvokedServer.Forms
{
    partial class FrmStealerOptions
    {
        private IContainer components;

        protected override void Dispose(bool disposing)
        {
            if (disposing && this.components != null)
                this.components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            ComponentResourceManager resources = new ComponentResourceManager(typeof(FrmStealerOptions));
            this.GetBrowserLogsBtn = new Guna2GradientButton();
            this.LoginsCheckBox = new Guna2CheckBox();
            this.AutofillsCheckBox = new Guna2CheckBox();
            this.CookiesCheckBox = new Guna2CheckBox();
            this.CardsCheckBox = new Guna2CheckBox();
            this.CryptoextensionsCheckBox = new Guna2CheckBox();
            this.HistoryCheckBox = new Guna2CheckBox();
            this.DownloadsCheckBox = new Guna2CheckBox();
            this.label1 = new Label();
            this.guna2GradientPanel1 = new Guna2GradientPanel();
            this.guna2GradientPanel2 = new Guna2GradientPanel();
            this.label2 = new Label();
            this.DiscordCheckBox = new Guna2CheckBox();
            this.TelegramCheckBox = new Guna2CheckBox();
            this.SteamCheckBox = new Guna2CheckBox();
            this.ObsCheckBox = new Guna2CheckBox();
            this.NgrokCheckBox = new Guna2CheckBox();
            this.CryptoinfoCheckBox = new Guna2CheckBox();
            this.FoxmailCheckBox = new Guna2CheckBox();
            this.FilezillaCheckBox = new Guna2CheckBox();
            this.AddressesCheckBox = new Guna2CheckBox();
            this.SuspendLayout();
            this.GetBrowserLogsBtn.Animated = true;
            this.GetBrowserLogsBtn.AutoRoundedCorners = true;
            this.GetBrowserLogsBtn.BorderColor = Color.FromArgb(200, 0, 0);
            this.GetBrowserLogsBtn.BorderRadius = 2;
            this.GetBrowserLogsBtn.BorderThickness = 1;
            this.GetBrowserLogsBtn.DisabledState.BorderColor = Color.DarkGray;
            this.GetBrowserLogsBtn.DisabledState.CustomBorderColor = Color.DarkGray;
            this.GetBrowserLogsBtn.DisabledState.FillColor = Color.FromArgb(169, 169, 169);
            this.GetBrowserLogsBtn.DisabledState.FillColor2 = Color.FromArgb(169, 169, 169);
            this.GetBrowserLogsBtn.DisabledState.ForeColor = Color.FromArgb(141, 141, 141);
            this.GetBrowserLogsBtn.FillColor = Color.FromArgb(35, 35, 35);
            this.GetBrowserLogsBtn.FillColor2 = Color.FromArgb(100, 35, 35);
            this.GetBrowserLogsBtn.Font = new Font("Segoe UI", 9f, FontStyle.Bold);
            this.GetBrowserLogsBtn.ForeColor = Color.FromArgb(250, 0, 0);
            this.GetBrowserLogsBtn.GradientMode = LinearGradientMode.ForwardDiagonal;
            this.GetBrowserLogsBtn.Location = new Point(291, 225);
            this.GetBrowserLogsBtn.Name = "GetBrowserLogsBtn";
            this.GetBrowserLogsBtn.Size = new Size(180, 45);
            this.GetBrowserLogsBtn.TabIndex = 0;
            this.GetBrowserLogsBtn.Text = "Get Logs";
            this.GetBrowserLogsBtn.Click += new EventHandler(this.GetBrowserLogsBtn_Click);
            this.LoginsCheckBox.Animated = true;
            this.LoginsCheckBox.AutoSize = true;
            this.LoginsCheckBox.BorderStyle = DashStyle.Dot;
            this.LoginsCheckBox.Checked = true;
            this.LoginsCheckBox.CheckedState.BorderColor = Color.FromArgb(94, 148, (int)byte.MaxValue);
            this.LoginsCheckBox.CheckedState.BorderRadius = 0;
            this.LoginsCheckBox.CheckedState.BorderThickness = 0;
            this.LoginsCheckBox.CheckedState.FillColor = Color.FromArgb(250, 0, 0);
            this.LoginsCheckBox.CheckMarkColor = Color.Black;
            this.LoginsCheckBox.CheckState = CheckState.Checked;
            this.LoginsCheckBox.ForeColor = Color.White;
            this.LoginsCheckBox.Location = new Point(8, 50);
            this.LoginsCheckBox.Name = "LoginsCheckBox";
            this.LoginsCheckBox.Size = new Size(57, 17);
            this.LoginsCheckBox.TabIndex = 2;
            this.LoginsCheckBox.Text = "Logins";
            this.LoginsCheckBox.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
            this.LoginsCheckBox.UncheckedState.BorderRadius = 0;
            this.LoginsCheckBox.UncheckedState.BorderThickness = 0;
            this.LoginsCheckBox.UncheckedState.FillColor = Color.FromArgb(125, 137, 149);
            this.AutofillsCheckBox.Animated = true;
            this.AutofillsCheckBox.AutoSize = true;
            this.AutofillsCheckBox.BorderStyle = DashStyle.Dot;
            this.AutofillsCheckBox.Checked = true;
            this.AutofillsCheckBox.CheckedState.BorderColor = Color.FromArgb(94, 148, (int)byte.MaxValue);
            this.AutofillsCheckBox.CheckedState.BorderRadius = 0;
            this.AutofillsCheckBox.CheckedState.BorderThickness = 0;
            this.AutofillsCheckBox.CheckedState.FillColor = Color.FromArgb(250, 0, 0);
            this.AutofillsCheckBox.CheckMarkColor = Color.Black;
            this.AutofillsCheckBox.CheckState = CheckState.Checked;
            this.AutofillsCheckBox.ForeColor = Color.White;
            this.AutofillsCheckBox.Location = new Point(8, 73);
            this.AutofillsCheckBox.Name = "AutofillsCheckBox";
            this.AutofillsCheckBox.Size = new Size(62, 17);
            this.AutofillsCheckBox.TabIndex = 3;
            this.AutofillsCheckBox.Text = "Autofills";
            this.AutofillsCheckBox.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
            this.AutofillsCheckBox.UncheckedState.BorderRadius = 0;
            this.AutofillsCheckBox.UncheckedState.BorderThickness = 0;
            this.AutofillsCheckBox.UncheckedState.FillColor = Color.FromArgb(125, 137, 149);
            this.CookiesCheckBox.Animated = true;
            this.CookiesCheckBox.AutoSize = true;
            this.CookiesCheckBox.BorderStyle = DashStyle.Dot;
            this.CookiesCheckBox.Checked = true;
            this.CookiesCheckBox.CheckedState.BorderColor = Color.FromArgb(94, 148, (int)byte.MaxValue);
            this.CookiesCheckBox.CheckedState.BorderRadius = 0;
            this.CookiesCheckBox.CheckedState.BorderThickness = 0;
            this.CookiesCheckBox.CheckedState.FillColor = Color.FromArgb(250, 0, 0);
            this.CookiesCheckBox.CheckMarkColor = Color.Black;
            this.CookiesCheckBox.CheckState = CheckState.Checked;
            this.CookiesCheckBox.ForeColor = Color.White;
            this.CookiesCheckBox.Location = new Point(8, 96);
            this.CookiesCheckBox.Name = "CookiesCheckBox";
            this.CookiesCheckBox.Size = new Size(64, 17);
            this.CookiesCheckBox.TabIndex = 4;
            this.CookiesCheckBox.Text = "Cookies";
            this.CookiesCheckBox.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
            this.CookiesCheckBox.UncheckedState.BorderRadius = 0;
            this.CookiesCheckBox.UncheckedState.BorderThickness = 0;
            this.CookiesCheckBox.UncheckedState.FillColor = Color.FromArgb(125, 137, 149);
            this.CardsCheckBox.Animated = true;
            this.CardsCheckBox.AutoSize = true;
            this.CardsCheckBox.BorderStyle = DashStyle.Dot;
            this.CardsCheckBox.Checked = true;
            this.CardsCheckBox.CheckedState.BorderColor = Color.FromArgb(94, 148, (int)byte.MaxValue);
            this.CardsCheckBox.CheckedState.BorderRadius = 0;
            this.CardsCheckBox.CheckedState.BorderThickness = 0;
            this.CardsCheckBox.CheckedState.FillColor = Color.FromArgb(250, 0, 0);
            this.CardsCheckBox.CheckMarkColor = Color.Black;
            this.CardsCheckBox.CheckState = CheckState.Checked;
            this.CardsCheckBox.ForeColor = Color.White;
            this.CardsCheckBox.Location = new Point(8, 119);
            this.CardsCheckBox.Name = "CardsCheckBox";
            this.CardsCheckBox.Size = new Size(83, 17);
            this.CardsCheckBox.TabIndex = 5;
            this.CardsCheckBox.Text = "Credit Cards";
            this.CardsCheckBox.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
            this.CardsCheckBox.UncheckedState.BorderRadius = 0;
            this.CardsCheckBox.UncheckedState.BorderThickness = 0;
            this.CardsCheckBox.UncheckedState.FillColor = Color.FromArgb(125, 137, 149);
            this.CryptoextensionsCheckBox.Animated = true;
            this.CryptoextensionsCheckBox.AutoSize = true;
            this.CryptoextensionsCheckBox.BorderStyle = DashStyle.Dot;
            this.CryptoextensionsCheckBox.Checked = true;
            this.CryptoextensionsCheckBox.CheckedState.BorderColor = Color.FromArgb(94, 148, (int)byte.MaxValue);
            this.CryptoextensionsCheckBox.CheckedState.BorderRadius = 0;
            this.CryptoextensionsCheckBox.CheckedState.BorderThickness = 0;
            this.CryptoextensionsCheckBox.CheckedState.FillColor = Color.FromArgb(250, 0, 0);
            this.CryptoextensionsCheckBox.CheckMarkColor = Color.Black;
            this.CryptoextensionsCheckBox.CheckState = CheckState.Checked;
            this.CryptoextensionsCheckBox.ForeColor = Color.White;
            this.CryptoextensionsCheckBox.Location = new Point((int)sbyte.MaxValue, 50);
            this.CryptoextensionsCheckBox.Name = "CryptoextensionsCheckBox";
            this.CryptoextensionsCheckBox.Size = new Size(110, 17);
            this.CryptoextensionsCheckBox.TabIndex = 6;
            this.CryptoextensionsCheckBox.Text = "Crypto Extensions";
            this.CryptoextensionsCheckBox.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
            this.CryptoextensionsCheckBox.UncheckedState.BorderRadius = 0;
            this.CryptoextensionsCheckBox.UncheckedState.BorderThickness = 0;
            this.CryptoextensionsCheckBox.UncheckedState.FillColor = Color.FromArgb(125, 137, 149);
            this.HistoryCheckBox.Animated = true;
            this.HistoryCheckBox.AutoSize = true;
            this.HistoryCheckBox.BorderStyle = DashStyle.Dot;
            this.HistoryCheckBox.CheckedState.BorderColor = Color.FromArgb(94, 148, (int)byte.MaxValue);
            this.HistoryCheckBox.CheckedState.BorderRadius = 0;
            this.HistoryCheckBox.CheckedState.BorderThickness = 0;
            this.HistoryCheckBox.CheckedState.FillColor = Color.FromArgb(250, 0, 0);
            this.HistoryCheckBox.CheckMarkColor = Color.Black;
            this.HistoryCheckBox.ForeColor = Color.White;
            this.HistoryCheckBox.Location = new Point((int)sbyte.MaxValue, 73);
            this.HistoryCheckBox.Name = "HistoryCheckBox";
            this.HistoryCheckBox.Size = new Size(99, 17);
            this.HistoryCheckBox.TabIndex = 7;
            this.HistoryCheckBox.Text = "Browser History";
            this.HistoryCheckBox.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
            this.HistoryCheckBox.UncheckedState.BorderRadius = 0;
            this.HistoryCheckBox.UncheckedState.BorderThickness = 0;
            this.HistoryCheckBox.UncheckedState.FillColor = Color.FromArgb(125, 137, 149);
            this.DownloadsCheckBox.Animated = true;
            this.DownloadsCheckBox.AutoSize = true;
            this.DownloadsCheckBox.BorderStyle = DashStyle.Dot;
            this.DownloadsCheckBox.CheckedState.BorderColor = Color.FromArgb(94, 148, (int)byte.MaxValue);
            this.DownloadsCheckBox.CheckedState.BorderRadius = 0;
            this.DownloadsCheckBox.CheckedState.BorderThickness = 0;
            this.DownloadsCheckBox.CheckedState.FillColor = Color.FromArgb(250, 0, 0);
            this.DownloadsCheckBox.CheckMarkColor = Color.Black;
            this.DownloadsCheckBox.ForeColor = Color.White;
            this.DownloadsCheckBox.Location = new Point((int)sbyte.MaxValue, 96);
            this.DownloadsCheckBox.Name = "DownloadsCheckBox";
            this.DownloadsCheckBox.Size = new Size(114, 17);
            this.DownloadsCheckBox.TabIndex = 8;
            this.DownloadsCheckBox.Text = "Downloads History";
            this.DownloadsCheckBox.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
            this.DownloadsCheckBox.UncheckedState.BorderRadius = 0;
            this.DownloadsCheckBox.UncheckedState.BorderThickness = 0;
            this.DownloadsCheckBox.UncheckedState.FillColor = Color.FromArgb(125, 137, 149);
            this.label1.AutoSize = true;
            this.label1.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte)0);
            this.label1.ForeColor = Color.White;
            this.label1.Location = new Point(5, 18);
            this.label1.Name = "label1";
            this.label1.Size = new Size(103, 13);
            this.label1.TabIndex = 9;
            this.label1.Text = "Browser Options:";
            this.guna2GradientPanel1.FillColor = Color.FromArgb(35, 35, 35);
            this.guna2GradientPanel1.FillColor2 = Color.FromArgb(250, 0, 0);
            this.guna2GradientPanel1.Location = new Point(8, 34);
            this.guna2GradientPanel1.Name = "guna2GradientPanel1";
            this.guna2GradientPanel1.Size = new Size(242, 3);
            this.guna2GradientPanel1.TabIndex = 10;
            this.guna2GradientPanel2.FillColor = Color.FromArgb(35, 35, 35);
            this.guna2GradientPanel2.FillColor2 = Color.FromArgb(250, 0, 0);
            this.guna2GradientPanel2.Location = new Point(8, 175);
            this.guna2GradientPanel2.Name = "guna2GradientPanel2";
            this.guna2GradientPanel2.Size = new Size(242, 3);
            this.guna2GradientPanel2.TabIndex = 12;
            this.label2.AutoSize = true;
            this.label2.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte)0);
            this.label2.ForeColor = Color.White;
            this.label2.Location = new Point(5, 159);
            this.label2.Name = "label2";
            this.label2.Size = new Size(121, 13);
            this.label2.TabIndex = 11;
            this.label2.Text = "Application Options:";
            this.DiscordCheckBox.Animated = true;
            this.DiscordCheckBox.AutoSize = true;
            this.DiscordCheckBox.BorderStyle = DashStyle.Dot;
            this.DiscordCheckBox.Checked = true;
            this.DiscordCheckBox.CheckedState.BorderColor = Color.FromArgb(94, 148, (int)byte.MaxValue);
            this.DiscordCheckBox.CheckedState.BorderRadius = 0;
            this.DiscordCheckBox.CheckedState.BorderThickness = 0;
            this.DiscordCheckBox.CheckedState.FillColor = Color.FromArgb(250, 0, 0);
            this.DiscordCheckBox.CheckMarkColor = Color.Black;
            this.DiscordCheckBox.CheckState = CheckState.Checked;
            this.DiscordCheckBox.ForeColor = Color.White;
            this.DiscordCheckBox.Location = new Point(8, 184);
            this.DiscordCheckBox.Name = "DiscordCheckBox";
            this.DiscordCheckBox.Size = new Size(101, 17);
            this.DiscordCheckBox.TabIndex = 13;
            this.DiscordCheckBox.Text = "Discord Tokens";
            this.DiscordCheckBox.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
            this.DiscordCheckBox.UncheckedState.BorderRadius = 0;
            this.DiscordCheckBox.UncheckedState.BorderThickness = 0;
            this.DiscordCheckBox.UncheckedState.FillColor = Color.FromArgb(125, 137, 149);
            this.TelegramCheckBox.Animated = true;
            this.TelegramCheckBox.AutoSize = true;
            this.TelegramCheckBox.BorderStyle = DashStyle.Dot;
            this.TelegramCheckBox.CheckedState.BorderColor = Color.FromArgb(94, 148, (int)byte.MaxValue);
            this.TelegramCheckBox.CheckedState.BorderRadius = 0;
            this.TelegramCheckBox.CheckedState.BorderThickness = 0;
            this.TelegramCheckBox.CheckedState.FillColor = Color.FromArgb(250, 0, 0);
            this.TelegramCheckBox.CheckMarkColor = Color.Black;
            this.TelegramCheckBox.Enabled = false;
            this.TelegramCheckBox.ForeColor = Color.White;
            this.TelegramCheckBox.Location = new Point(8, 207);
            this.TelegramCheckBox.Name = "TelegramCheckBox";
            this.TelegramCheckBox.Size = new Size(91, 17);
            this.TelegramCheckBox.TabIndex = 14;
            this.TelegramCheckBox.Text = "Telegram Info";
            this.TelegramCheckBox.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
            this.TelegramCheckBox.UncheckedState.BorderRadius = 0;
            this.TelegramCheckBox.UncheckedState.BorderThickness = 0;
            this.TelegramCheckBox.UncheckedState.FillColor = Color.FromArgb(125, 137, 149);
            this.SteamCheckBox.Animated = true;
            this.SteamCheckBox.AutoSize = true;
            this.SteamCheckBox.BorderStyle = DashStyle.Dot;
            this.SteamCheckBox.CheckedState.BorderColor = Color.FromArgb(94, 148, (int)byte.MaxValue);
            this.SteamCheckBox.CheckedState.BorderRadius = 0;
            this.SteamCheckBox.CheckedState.BorderThickness = 0;
            this.SteamCheckBox.CheckedState.FillColor = Color.FromArgb(250, 0, 0);
            this.SteamCheckBox.CheckMarkColor = Color.Black;
            this.SteamCheckBox.Enabled = false;
            this.SteamCheckBox.ForeColor = Color.White;
            this.SteamCheckBox.Location = new Point(8, 230);
            this.SteamCheckBox.Name = "SteamCheckBox";
            this.SteamCheckBox.Size = new Size(82, 17);
            this.SteamCheckBox.TabIndex = 15;
            this.SteamCheckBox.Text = "Steam Keys";
            this.SteamCheckBox.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
            this.SteamCheckBox.UncheckedState.BorderRadius = 0;
            this.SteamCheckBox.UncheckedState.BorderThickness = 0;
            this.SteamCheckBox.UncheckedState.FillColor = Color.FromArgb(125, 137, 149);
            this.ObsCheckBox.Animated = true;
            this.ObsCheckBox.AutoSize = true;
            this.ObsCheckBox.BorderStyle = DashStyle.Dot;
            this.ObsCheckBox.Checked = true;
            this.ObsCheckBox.CheckedState.BorderColor = Color.FromArgb(94, 148, (int)byte.MaxValue);
            this.ObsCheckBox.CheckedState.BorderRadius = 0;
            this.ObsCheckBox.CheckedState.BorderThickness = 0;
            this.ObsCheckBox.CheckedState.FillColor = Color.FromArgb(250, 0, 0);
            this.ObsCheckBox.CheckMarkColor = Color.Black;
            this.ObsCheckBox.CheckState = CheckState.Checked;
            this.ObsCheckBox.ForeColor = Color.White;
            this.ObsCheckBox.Location = new Point((int)sbyte.MaxValue, 184);
            this.ObsCheckBox.Name = "ObsCheckBox";
            this.ObsCheckBox.Size = new Size(74, 17);
            this.ObsCheckBox.TabIndex = 16;
            this.ObsCheckBox.Text = "OBS Keys";
            this.ObsCheckBox.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
            this.ObsCheckBox.UncheckedState.BorderRadius = 0;
            this.ObsCheckBox.UncheckedState.BorderThickness = 0;
            this.ObsCheckBox.UncheckedState.FillColor = Color.FromArgb(125, 137, 149);
            this.NgrokCheckBox.Animated = true;
            this.NgrokCheckBox.AutoSize = true;
            this.NgrokCheckBox.BorderStyle = DashStyle.Dot;
            this.NgrokCheckBox.CheckedState.BorderColor = Color.FromArgb(94, 148, (int)byte.MaxValue);
            this.NgrokCheckBox.CheckedState.BorderRadius = 0;
            this.NgrokCheckBox.CheckedState.BorderThickness = 0;
            this.NgrokCheckBox.CheckedState.FillColor = Color.FromArgb(250, 0, 0);
            this.NgrokCheckBox.CheckMarkColor = Color.Black;
            this.NgrokCheckBox.Enabled = false;
            this.NgrokCheckBox.ForeColor = Color.White;
            this.NgrokCheckBox.Location = new Point((int)sbyte.MaxValue, 207);
            this.NgrokCheckBox.Name = "NgrokCheckBox";
            this.NgrokCheckBox.Size = new Size(106, 17);
            this.NgrokCheckBox.TabIndex = 17;
            this.NgrokCheckBox.Text = "Ngrok Auth Keys";
            this.NgrokCheckBox.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
            this.NgrokCheckBox.UncheckedState.BorderRadius = 0;
            this.NgrokCheckBox.UncheckedState.BorderThickness = 0;
            this.NgrokCheckBox.UncheckedState.FillColor = Color.FromArgb(125, 137, 149);
            this.CryptoinfoCheckBox.Animated = true;
            this.CryptoinfoCheckBox.AutoSize = true;
            this.CryptoinfoCheckBox.BorderStyle = DashStyle.Dot;
            this.CryptoinfoCheckBox.Checked = true;
            this.CryptoinfoCheckBox.CheckedState.BorderColor = Color.FromArgb(94, 148, (int)byte.MaxValue);
            this.CryptoinfoCheckBox.CheckedState.BorderRadius = 0;
            this.CryptoinfoCheckBox.CheckedState.BorderThickness = 0;
            this.CryptoinfoCheckBox.CheckedState.FillColor = Color.FromArgb(250, 0, 0);
            this.CryptoinfoCheckBox.CheckMarkColor = Color.Black;
            this.CryptoinfoCheckBox.CheckState = CheckState.Checked;
            this.CryptoinfoCheckBox.ForeColor = Color.White;
            this.CryptoinfoCheckBox.Location = new Point((int)sbyte.MaxValue, 230);
            this.CryptoinfoCheckBox.Name = "CryptoinfoCheckBox";
            this.CryptoinfoCheckBox.Size = new Size(77, 17);
            this.CryptoinfoCheckBox.TabIndex = 18;
            this.CryptoinfoCheckBox.Text = "Crypto Info";
            this.CryptoinfoCheckBox.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
            this.CryptoinfoCheckBox.UncheckedState.BorderRadius = 0;
            this.CryptoinfoCheckBox.UncheckedState.BorderThickness = 0;
            this.CryptoinfoCheckBox.UncheckedState.FillColor = Color.FromArgb(125, 137, 149);
            this.FoxmailCheckBox.Animated = true;
            this.FoxmailCheckBox.AutoSize = true;
            this.FoxmailCheckBox.BorderStyle = DashStyle.Dot;
            this.FoxmailCheckBox.Checked = true;
            this.FoxmailCheckBox.CheckedState.BorderColor = Color.FromArgb(94, 148, (int)byte.MaxValue);
            this.FoxmailCheckBox.CheckedState.BorderRadius = 0;
            this.FoxmailCheckBox.CheckedState.BorderThickness = 0;
            this.FoxmailCheckBox.CheckedState.FillColor = Color.FromArgb(250, 0, 0);
            this.FoxmailCheckBox.CheckMarkColor = Color.Black;
            this.FoxmailCheckBox.CheckState = CheckState.Checked;
            this.FoxmailCheckBox.ForeColor = Color.White;
            this.FoxmailCheckBox.Location = new Point((int)sbyte.MaxValue, 253);
            this.FoxmailCheckBox.Name = "FoxmailCheckBox";
            this.FoxmailCheckBox.Size = new Size(115, 17);
            this.FoxmailCheckBox.TabIndex = 20;
            this.FoxmailCheckBox.Text = "Foxmail Passwords";
            this.FoxmailCheckBox.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
            this.FoxmailCheckBox.UncheckedState.BorderRadius = 0;
            this.FoxmailCheckBox.UncheckedState.BorderThickness = 0;
            this.FoxmailCheckBox.UncheckedState.FillColor = Color.FromArgb(125, 137, 149);
            this.FilezillaCheckBox.Animated = true;
            this.FilezillaCheckBox.AutoSize = true;
            this.FilezillaCheckBox.BorderStyle = DashStyle.Dot;
            this.FilezillaCheckBox.Checked = true;
            this.FilezillaCheckBox.CheckedState.BorderColor = Color.FromArgb(94, 148, (int)byte.MaxValue);
            this.FilezillaCheckBox.CheckedState.BorderRadius = 0;
            this.FilezillaCheckBox.CheckedState.BorderThickness = 0;
            this.FilezillaCheckBox.CheckedState.FillColor = Color.FromArgb(250, 0, 0);
            this.FilezillaCheckBox.CheckMarkColor = Color.Black;
            this.FilezillaCheckBox.CheckState = CheckState.Checked;
            this.FilezillaCheckBox.ForeColor = Color.White;
            this.FilezillaCheckBox.Location = new Point(8, 253);
            this.FilezillaCheckBox.Name = "FilezillaCheckBox";
            this.FilezillaCheckBox.Size = new Size(115, 17);
            this.FilezillaCheckBox.TabIndex = 19;
            this.FilezillaCheckBox.Text = "FilaZilla Passwords";
            this.FilezillaCheckBox.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
            this.FilezillaCheckBox.UncheckedState.BorderRadius = 0;
            this.FilezillaCheckBox.UncheckedState.BorderThickness = 0;
            this.FilezillaCheckBox.UncheckedState.FillColor = Color.FromArgb(125, 137, 149);
            this.AddressesCheckBox.Animated = true;
            this.AddressesCheckBox.AutoSize = true;
            this.AddressesCheckBox.BorderStyle = DashStyle.Dot;
            this.AddressesCheckBox.CheckedState.BorderColor = Color.FromArgb(94, 148, (int)byte.MaxValue);
            this.AddressesCheckBox.CheckedState.BorderRadius = 0;
            this.AddressesCheckBox.CheckedState.BorderThickness = 0;
            this.AddressesCheckBox.CheckedState.FillColor = Color.FromArgb(250, 0, 0);
            this.AddressesCheckBox.CheckMarkColor = Color.Black;
            this.AddressesCheckBox.Enabled = false;
            this.AddressesCheckBox.ForeColor = Color.White;
            this.AddressesCheckBox.Location = new Point((int)sbyte.MaxValue, 119);
            this.AddressesCheckBox.Name = "AddressesCheckBox";
            this.AddressesCheckBox.Size = new Size(109, 17);
            this.AddressesCheckBox.TabIndex = 21;
            this.AddressesCheckBox.Text = "Saved Addresses";
            this.AddressesCheckBox.UncheckedState.BorderColor = Color.FromArgb(125, 137, 149);
            this.AddressesCheckBox.UncheckedState.BorderRadius = 0;
            this.AddressesCheckBox.UncheckedState.BorderThickness = 0;
            this.AddressesCheckBox.UncheckedState.FillColor = Color.FromArgb(125, 137, 149);
            this.AutoScaleDimensions = new SizeF(6f, 13f);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = Color.FromArgb(35, 35, 35);
            this.ClientSize = new Size(483, 290);
            this.Controls.Add((Control)this.AddressesCheckBox);
            this.Controls.Add((Control)this.FoxmailCheckBox);
            this.Controls.Add((Control)this.FilezillaCheckBox);
            this.Controls.Add((Control)this.CryptoinfoCheckBox);
            this.Controls.Add((Control)this.NgrokCheckBox);
            this.Controls.Add((Control)this.ObsCheckBox);
            this.Controls.Add((Control)this.SteamCheckBox);
            this.Controls.Add((Control)this.TelegramCheckBox);
            this.Controls.Add((Control)this.DiscordCheckBox);
            this.Controls.Add((Control)this.guna2GradientPanel2);
            this.Controls.Add((Control)this.label2);
            this.Controls.Add((Control)this.guna2GradientPanel1);
            this.Controls.Add((Control)this.label1);
            this.Controls.Add((Control)this.DownloadsCheckBox);
            this.Controls.Add((Control)this.HistoryCheckBox);
            this.Controls.Add((Control)this.CryptoextensionsCheckBox);
            this.Controls.Add((Control)this.CardsCheckBox);
            this.Controls.Add((Control)this.CookiesCheckBox);
            this.Controls.Add((Control)this.AutofillsCheckBox);
            this.Controls.Add((Control)this.LoginsCheckBox);
            this.Controls.Add((Control)this.GetBrowserLogsBtn);
            this.Icon = (Icon)resources.GetObject("$this.Icon");
            this.Name = "FrmStealerOptions";
            this.StartPosition = FormStartPosition.CenterScreen;
            this.Text = "FrmStealerBrowserOptions";
            this.Load += new EventHandler(this.FrmStealerOptions_Load);
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private Guna2GradientButton GetBrowserLogsBtn;
        private Guna2CheckBox LoginsCheckBox;
        private Guna2CheckBox AutofillsCheckBox;
        private Guna2CheckBox CookiesCheckBox;
        private Guna2CheckBox CardsCheckBox;
        private Guna2CheckBox CryptoextensionsCheckBox;
        private Guna2CheckBox HistoryCheckBox;
        private Guna2CheckBox DownloadsCheckBox;
        private Label label1;
        private Guna2GradientPanel guna2GradientPanel1;
        private Guna2GradientPanel guna2GradientPanel2;
        private Label label2;
        private Guna2CheckBox DiscordCheckBox;
        private Guna2CheckBox TelegramCheckBox;
        private Guna2CheckBox SteamCheckBox;
        private Guna2CheckBox ObsCheckBox;
        private Guna2CheckBox NgrokCheckBox;
        private Guna2CheckBox CryptoinfoCheckBox;
        private Guna2CheckBox FoxmailCheckBox;
        private Guna2CheckBox FilezillaCheckBox;
        private Guna2CheckBox AddressesCheckBox;
    }
}
